<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4 Regression with Counts as Outcomes | Generalized Linear Mixed Models with R: A tutorial</title>
  <meta name="description" content="4 Regression with Counts as Outcomes | Generalized Linear Mixed Models with R: A tutorial" />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="4 Regression with Counts as Outcomes | Generalized Linear Mixed Models with R: A tutorial" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4 Regression with Counts as Outcomes | Generalized Linear Mixed Models with R: A tutorial" />
  
  
  

<meta name="author" content="Rick Hass" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="logistic-regression.html"/>
<link rel="next" href="model-fit-and-assumptions-for-glms.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Overview</a></li>
<li class="chapter" data-level="1" data-path="r-basics.html"><a href="r-basics.html"><i class="fa fa-check"></i><b>1</b> R Basics</a>
<ul>
<li class="chapter" data-level="1.1" data-path="r-basics.html"><a href="r-basics.html#what-is-coding"><i class="fa fa-check"></i><b>1.1</b> What is “coding”</a></li>
<li class="chapter" data-level="1.2" data-path="r-basics.html"><a href="r-basics.html#r-console-versus-the-rstudio-script"><i class="fa fa-check"></i><b>1.2</b> R Console versus the RStudio Script</a></li>
<li class="chapter" data-level="1.3" data-path="r-basics.html"><a href="r-basics.html#working-with-data"><i class="fa fa-check"></i><b>1.3</b> Working with data</a></li>
<li class="chapter" data-level="1.4" data-path="r-basics.html"><a href="r-basics.html#using-a-script-to-generate-data-and-computing-the-mean-and-standard-deviation"><i class="fa fa-check"></i><b>1.4</b> Using a script to generate data, and computing the mean and standard deviation</a></li>
<li class="chapter" data-level="1.5" data-path="r-basics.html"><a href="r-basics.html#importing-data"><i class="fa fa-check"></i><b>1.5</b> Importing Data</a></li>
<li class="chapter" data-level="1.6" data-path="r-basics.html"><a href="r-basics.html#reading-in-an-spss-file"><i class="fa fa-check"></i><b>1.6</b> Reading in an SPSS file</a>
<ul>
<li class="chapter" data-level="1.6.1" data-path="r-basics.html"><a href="r-basics.html#a-quick-note-on-indexing"><i class="fa fa-check"></i><b>1.6.1</b> A quick note on indexing</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="r-basics.html"><a href="r-basics.html#frequencies-and-contingency-tables"><i class="fa fa-check"></i><b>1.7</b> Frequencies and Contingency Tables</a></li>
<li class="chapter" data-level="1.8" data-path="r-basics.html"><a href="r-basics.html#descriptive-statistics"><i class="fa fa-check"></i><b>1.8</b> Descriptive statistics</a>
<ul>
<li class="chapter" data-level="1.8.1" data-path="r-basics.html"><a href="r-basics.html#the-describe-function"><i class="fa fa-check"></i><b>1.8.1</b> The describe function</a></li>
<li class="chapter" data-level="1.8.2" data-path="r-basics.html"><a href="r-basics.html#the-describeby-function"><i class="fa fa-check"></i><b>1.8.2</b> The describeBy function</a></li>
<li class="chapter" data-level="1.8.3" data-path="r-basics.html"><a href="r-basics.html#computing-a-new-variable-and-adding-it-to-the-dataframe"><i class="fa fa-check"></i><b>1.8.3</b> Computing a new variable and adding it to the dataframe</a></li>
</ul></li>
<li class="chapter" data-level="1.9" data-path="r-basics.html"><a href="r-basics.html#visualizing-data"><i class="fa fa-check"></i><b>1.9</b> Visualizing Data</a>
<ul>
<li class="chapter" data-level="1.9.1" data-path="r-basics.html"><a href="r-basics.html#histograms-and-density-plots"><i class="fa fa-check"></i><b>1.9.1</b> Histograms and density plots</a></li>
<li class="chapter" data-level="1.9.2" data-path="r-basics.html"><a href="r-basics.html#boxplots"><i class="fa fa-check"></i><b>1.9.2</b> Boxplots</a></li>
<li class="chapter" data-level="1.9.3" data-path="r-basics.html"><a href="r-basics.html#scatterplots"><i class="fa fa-check"></i><b>1.9.3</b> Scatterplots</a></li>
</ul></li>
<li class="chapter" data-level="1.10" data-path="r-basics.html"><a href="r-basics.html#review"><i class="fa fa-check"></i><b>1.10</b> Review</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="ordinary-linear-regression.html"><a href="ordinary-linear-regression.html"><i class="fa fa-check"></i><b>2</b> Ordinary Linear Regression</a>
<ul>
<li class="chapter" data-level="2.1" data-path="ordinary-linear-regression.html"><a href="ordinary-linear-regression.html#our-data"><i class="fa fa-check"></i><b>2.1</b> Our data</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="ordinary-linear-regression.html"><a href="ordinary-linear-regression.html#converting-from-numeric-to-factor"><i class="fa fa-check"></i><b>2.1.1</b> Converting from numeric to factor</a></li>
<li class="chapter" data-level="2.1.2" data-path="ordinary-linear-regression.html"><a href="ordinary-linear-regression.html#confidence-intervals-v.-p-values"><i class="fa fa-check"></i><b>2.1.2</b> Confidence Intervals v. p-values</a></li>
<li class="chapter" data-level="2.1.3" data-path="ordinary-linear-regression.html"><a href="ordinary-linear-regression.html#adding-interaction-terms"><i class="fa fa-check"></i><b>2.1.3</b> Adding interaction terms</a></li>
<li class="chapter" data-level="2.1.4" data-path="ordinary-linear-regression.html"><a href="ordinary-linear-regression.html#interaction-model-for-gambling"><i class="fa fa-check"></i><b>2.1.4</b> Interaction model for Gambling</a></li>
<li class="chapter" data-level="2.1.5" data-path="ordinary-linear-regression.html"><a href="ordinary-linear-regression.html#interaction-output"><i class="fa fa-check"></i><b>2.1.5</b> Interaction Output</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="ordinary-linear-regression.html"><a href="ordinary-linear-regression.html#anova-and-drop1-commands"><i class="fa fa-check"></i><b>2.2</b> ANOVA and drop1 commands</a></li>
<li class="chapter" data-level="2.3" data-path="ordinary-linear-regression.html"><a href="ordinary-linear-regression.html#plots"><i class="fa fa-check"></i><b>2.3</b> Plots</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>3</b> Logistic Regression</a>
<ul>
<li class="chapter" data-level="3.1" data-path="logistic-regression.html"><a href="logistic-regression.html#an-example-diabetes-risk-factors"><i class="fa fa-check"></i><b>3.1</b> An Example: Diabetes risk factors</a></li>
<li class="chapter" data-level="3.2" data-path="logistic-regression.html"><a href="logistic-regression.html#model-discrimination-and-fit"><i class="fa fa-check"></i><b>3.2</b> Model Discrimination and Fit</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="logistic-regression.html"><a href="logistic-regression.html#roc-and-auroc"><i class="fa fa-check"></i><b>3.2.1</b> ROC and AUROC</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="regression-with-counts-as-outcomes.html"><a href="regression-with-counts-as-outcomes.html"><i class="fa fa-check"></i><b>4</b> Regression with Counts as Outcomes</a>
<ul>
<li class="chapter" data-level="4.1" data-path="regression-with-counts-as-outcomes.html"><a href="regression-with-counts-as-outcomes.html#example-data-phmc-fruits-question"><i class="fa fa-check"></i><b>4.1</b> Example data: PHMC Fruits question</a></li>
<li class="chapter" data-level="4.2" data-path="regression-with-counts-as-outcomes.html"><a href="regression-with-counts-as-outcomes.html#coefficients-in-poisson-models"><i class="fa fa-check"></i><b>4.2</b> Coefficients in Poisson Models</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="regression-with-counts-as-outcomes.html"><a href="regression-with-counts-as-outcomes.html#exponentiated-coefficients-interpretation"><i class="fa fa-check"></i><b>4.2.1</b> Exponentiated Coefficients Interpretation</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="regression-with-counts-as-outcomes.html"><a href="regression-with-counts-as-outcomes.html#overdispersion-and-other-count-regression-models"><i class="fa fa-check"></i><b>4.3</b> Overdispersion and other count regression models</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="regression-with-counts-as-outcomes.html"><a href="regression-with-counts-as-outcomes.html#overdispersion-and-zero-inflation"><i class="fa fa-check"></i><b>4.3.1</b> Overdispersion and Zero-inflation</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="regression-with-counts-as-outcomes.html"><a href="regression-with-counts-as-outcomes.html#zero-inflated-models"><i class="fa fa-check"></i><b>4.4</b> Zero-inflated models</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="model-fit-and-assumptions-for-glms.html"><a href="model-fit-and-assumptions-for-glms.html"><i class="fa fa-check"></i><b>5</b> Model Fit and Assumptions for GLMs</a>
<ul>
<li class="chapter" data-level="5.1" data-path="model-fit-and-assumptions-for-glms.html"><a href="model-fit-and-assumptions-for-glms.html#model-checking-and-diagnostics-in-ordinary-least-squares"><i class="fa fa-check"></i><b>5.1</b> Model Checking and Diagnostics in Ordinary Least Squares</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="model-fit-and-assumptions-for-glms.html"><a href="model-fit-and-assumptions-for-glms.html#residuals-v.-fitted-values"><i class="fa fa-check"></i><b>5.1.1</b> Residuals v. Fitted Values</a></li>
<li class="chapter" data-level="5.1.2" data-path="model-fit-and-assumptions-for-glms.html"><a href="model-fit-and-assumptions-for-glms.html#normalty-of-residuals"><i class="fa fa-check"></i><b>5.1.2</b> Normalty of residuals</a></li>
<li class="chapter" data-level="5.1.3" data-path="model-fit-and-assumptions-for-glms.html"><a href="model-fit-and-assumptions-for-glms.html#leverage"><i class="fa fa-check"></i><b>5.1.3</b> Leverage</a></li>
<li class="chapter" data-level="5.1.4" data-path="model-fit-and-assumptions-for-glms.html"><a href="model-fit-and-assumptions-for-glms.html#influence"><i class="fa fa-check"></i><b>5.1.4</b> Influence</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="model-fit-and-assumptions-for-glms.html"><a href="model-fit-and-assumptions-for-glms.html#model-checking-and-diagnostics-in-logistic-regression"><i class="fa fa-check"></i><b>5.2</b> Model Checking and Diagnostics in Logistic Regression</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="model-fit-and-assumptions-for-glms.html"><a href="model-fit-and-assumptions-for-glms.html#hosmer-lemeshow-test"><i class="fa fa-check"></i><b>5.2.1</b> Hosmer-Lemeshow Test</a></li>
<li class="chapter" data-level="5.2.2" data-path="model-fit-and-assumptions-for-glms.html"><a href="model-fit-and-assumptions-for-glms.html#nagelkerkes-pseudo-r-squared"><i class="fa fa-check"></i><b>5.2.2</b> Nagelkerke’s pseudo R-squared</a></li>
<li class="chapter" data-level="5.2.3" data-path="model-fit-and-assumptions-for-glms.html"><a href="model-fit-and-assumptions-for-glms.html#residuals-and-leverages"><i class="fa fa-check"></i><b>5.2.3</b> Residuals and leverages</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="model-fit-and-assumptions-for-glms.html"><a href="model-fit-and-assumptions-for-glms.html#summary"><i class="fa fa-check"></i><b>5.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="introducing-mixed-models-and-the-lme4-package.html"><a href="introducing-mixed-models-and-the-lme4-package.html"><i class="fa fa-check"></i><b>6</b> Introducing mixed-models and the lme4 package</a>
<ul>
<li class="chapter" data-level="6.1" data-path="introducing-mixed-models-and-the-lme4-package.html"><a href="introducing-mixed-models-and-the-lme4-package.html#options-in-r"><i class="fa fa-check"></i><b>6.1</b> Options in R</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="introducing-mixed-models-and-the-lme4-package.html"><a href="introducing-mixed-models-and-the-lme4-package.html#why-lme4"><i class="fa fa-check"></i><b>6.1.1</b> Why lme4?</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="introducing-mixed-models-and-the-lme4-package.html"><a href="introducing-mixed-models-and-the-lme4-package.html#a-possible-workflow"><i class="fa fa-check"></i><b>6.2</b> A possible workflow</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="introducing-mixed-models-and-the-lme4-package.html"><a href="introducing-mixed-models-and-the-lme4-package.html#high-school-and-beyond"><i class="fa fa-check"></i><b>6.2.1</b> High School and Beyond</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="introducing-mixed-models-and-the-lme4-package.html"><a href="introducing-mixed-models-and-the-lme4-package.html#model-1-one-way-random-effects-anova-using-reml"><i class="fa fa-check"></i><b>6.3</b> Model 1: one-way random-effects ANOVA using REML</a></li>
<li class="chapter" data-level="6.4" data-path="introducing-mixed-models-and-the-lme4-package.html"><a href="introducing-mixed-models-and-the-lme4-package.html#quasi-anova-estimator"><i class="fa fa-check"></i><b>6.4</b> Quasi-ANOVA estimator</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="introducing-mixed-models-and-the-lme4-package.html"><a href="introducing-mixed-models-and-the-lme4-package.html#unrestricted-maximum-likelihood"><i class="fa fa-check"></i><b>6.4.1</b> (unrestricted) Maximum Likelihood</a></li>
<li class="chapter" data-level="6.4.2" data-path="introducing-mixed-models-and-the-lme4-package.html"><a href="introducing-mixed-models-and-the-lme4-package.html#intraclass-correlation"><i class="fa fa-check"></i><b>6.4.2</b> Intraclass correlation</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="introducing-mixed-models-and-the-lme4-package.html"><a href="introducing-mixed-models-and-the-lme4-package.html#bootstrapped-confidence-intervals"><i class="fa fa-check"></i><b>6.5</b> Bootstrapped confidence intervals</a></li>
<li class="chapter" data-level="6.6" data-path="introducing-mixed-models-and-the-lme4-package.html"><a href="introducing-mixed-models-and-the-lme4-package.html#linear-mixed-effects"><i class="fa fa-check"></i><b>6.6</b> Linear mixed-effects</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="introducing-mixed-models-and-the-lme4-package.html"><a href="introducing-mixed-models-and-the-lme4-package.html#random-effects-estimates"><i class="fa fa-check"></i><b>6.6.1</b> Random effects estimates</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="mixed-models-as-hierarchical-linear-models.html"><a href="mixed-models-as-hierarchical-linear-models.html"><i class="fa fa-check"></i><b>7</b> Mixed models as Hierarchical Linear Models</a>
<ul>
<li class="chapter" data-level="7.1" data-path="mixed-models-as-hierarchical-linear-models.html"><a href="mixed-models-as-hierarchical-linear-models.html#high-school-and-beyond-data"><i class="fa fa-check"></i><b>7.1</b> High School and Beyond Data</a></li>
<li class="chapter" data-level="7.2" data-path="mixed-models-as-hierarchical-linear-models.html"><a href="mixed-models-as-hierarchical-linear-models.html#model-1-unconditional-model"><i class="fa fa-check"></i><b>7.2</b> Model 1: unconditional model</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="mixed-models-as-hierarchical-linear-models.html"><a href="mixed-models-as-hierarchical-linear-models.html#unconditional-icc"><i class="fa fa-check"></i><b>7.2.1</b> Unconditional ICC</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="mixed-models-as-hierarchical-linear-models.html"><a href="mixed-models-as-hierarchical-linear-models.html#means-as-outcomes-binary-predictor"><i class="fa fa-check"></i><b>7.3</b> Means as outcomes: Binary Predictor</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="mixed-models-as-hierarchical-linear-models.html"><a href="mixed-models-as-hierarchical-linear-models.html#means-as-outcomes-continuous-predictor"><i class="fa fa-check"></i><b>7.3.1</b> Means as outcomes: continuous predictor</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="mixed-models-as-hierarchical-linear-models.html"><a href="mixed-models-as-hierarchical-linear-models.html#multiple-hierarchical-linear-regression"><i class="fa fa-check"></i><b>7.4</b> Multiple hierarchical linear regression</a></li>
<li class="chapter" data-level="7.5" data-path="mixed-models-as-hierarchical-linear-models.html"><a href="mixed-models-as-hierarchical-linear-models.html#plotting-predictor-effects"><i class="fa fa-check"></i><b>7.5</b> Plotting predictor effects</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="more-on-hierarchical-linear-models.html"><a href="more-on-hierarchical-linear-models.html"><i class="fa fa-check"></i><b>8</b> More on Hierarchical Linear Models</a>
<ul>
<li class="chapter" data-level="8.1" data-path="more-on-hierarchical-linear-models.html"><a href="more-on-hierarchical-linear-models.html#overview-1"><i class="fa fa-check"></i><b>8.1</b> Overview</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="more-on-hierarchical-linear-models.html"><a href="more-on-hierarchical-linear-models.html#load-the-data"><i class="fa fa-check"></i><b>8.1.1</b> Load the data</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="more-on-hierarchical-linear-models.html"><a href="more-on-hierarchical-linear-models.html#random-coefficients-model"><i class="fa fa-check"></i><b>8.2</b> Random Coefficients model</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="more-on-hierarchical-linear-models.html"><a href="more-on-hierarchical-linear-models.html#visualizing-the-within-school-slopes"><i class="fa fa-check"></i><b>8.2.1</b> Visualizing the within-school slopes</a></li>
<li class="chapter" data-level="8.2.2" data-path="more-on-hierarchical-linear-models.html"><a href="more-on-hierarchical-linear-models.html#fitting-the-random-coefficients-2-level-model"><i class="fa fa-check"></i><b>8.2.2</b> Fitting the Random Coefficients 2-level model</a></li>
<li class="chapter" data-level="8.2.3" data-path="more-on-hierarchical-linear-models.html"><a href="more-on-hierarchical-linear-models.html#adding-additional-level-1-predictors-to-the-random-coefficients-model"><i class="fa fa-check"></i><b>8.2.3</b> Adding additional level-1 predictors to the random coefficients model</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="more-on-hierarchical-linear-models.html"><a href="more-on-hierarchical-linear-models.html#intercepts-and-slopes-as-outcomes"><i class="fa fa-check"></i><b>8.3</b> Intercepts and Slopes as Outcomes</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="more-on-hierarchical-linear-models.html"><a href="more-on-hierarchical-linear-models.html#interactions-and-the-iso-model"><i class="fa fa-check"></i><b>8.3.1</b> Interactions and the ISO model</a></li>
<li class="chapter" data-level="8.3.2" data-path="more-on-hierarchical-linear-models.html"><a href="more-on-hierarchical-linear-models.html#mean-ses-and-student-ses"><i class="fa fa-check"></i><b>8.3.2</b> Mean SES and Student SES</a></li>
<li class="chapter" data-level="8.3.3" data-path="more-on-hierarchical-linear-models.html"><a href="more-on-hierarchical-linear-models.html#sector-and-student-ses"><i class="fa fa-check"></i><b>8.3.3</b> Sector and Student SES</a></li>
<li class="chapter" data-level="8.3.4" data-path="more-on-hierarchical-linear-models.html"><a href="more-on-hierarchical-linear-models.html#visualizing-the-mean-ses-effect"><i class="fa fa-check"></i><b>8.3.4</b> Visualizing the mean SES effect</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="more-on-hierarchical-linear-models.html"><a href="more-on-hierarchical-linear-models.html#model-comparison-with-likelihood-ratios-fixed-and-random"><i class="fa fa-check"></i><b>8.4</b> Model comparison with Likelihood Ratios: Fixed and Random</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="more-on-hierarchical-linear-models.html"><a href="more-on-hierarchical-linear-models.html#example-1-lrt-for-fixed-effects"><i class="fa fa-check"></i><b>8.4.1</b> Example 1: LRT for fixed effects</a></li>
<li class="chapter" data-level="8.4.2" data-path="more-on-hierarchical-linear-models.html"><a href="more-on-hierarchical-linear-models.html#example-2-lrt-for-random-effects"><i class="fa fa-check"></i><b>8.4.2</b> Example 2: LRT for random effects</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="more-on-hierarchical-linear-models.html"><a href="more-on-hierarchical-linear-models.html#diagnostics"><i class="fa fa-check"></i><b>8.5</b> Diagnostics</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="using-lme4-to-fit-mlm-to-longitudinal-data.html"><a href="using-lme4-to-fit-mlm-to-longitudinal-data.html"><i class="fa fa-check"></i><b>9</b> Using lme4 to fit MLM to longitudinal data</a>
<ul>
<li class="chapter" data-level="9.1" data-path="using-lme4-to-fit-mlm-to-longitudinal-data.html"><a href="using-lme4-to-fit-mlm-to-longitudinal-data.html#data-description-average-reaction-time-per-day-for-subjects-in-a-sleep-deprivation-study-belenky-et-al.-2003"><i class="fa fa-check"></i><b>9.1</b> Data description: average reaction time per day for subjects in a sleep deprivation study (Belenky et al. 2003)</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="using-lme4-to-fit-mlm-to-longitudinal-data.html"><a href="using-lme4-to-fit-mlm-to-longitudinal-data.html#visualization-of-the-data"><i class="fa fa-check"></i><b>9.1.1</b> Visualization of the data</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="using-lme4-to-fit-mlm-to-longitudinal-data.html"><a href="using-lme4-to-fit-mlm-to-longitudinal-data.html#fitting-the-level-1-model"><i class="fa fa-check"></i><b>9.2</b> Fitting the level-1 model</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="using-lme4-to-fit-mlm-to-longitudinal-data.html"><a href="using-lme4-to-fit-mlm-to-longitudinal-data.html#model-equations"><i class="fa fa-check"></i><b>9.2.1</b> Model Equations</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="using-lme4-to-fit-mlm-to-longitudinal-data.html"><a href="using-lme4-to-fit-mlm-to-longitudinal-data.html#model-building"><i class="fa fa-check"></i><b>9.3</b> Model building</a></li>
<li class="chapter" data-level="9.4" data-path="using-lme4-to-fit-mlm-to-longitudinal-data.html"><a href="using-lme4-to-fit-mlm-to-longitudinal-data.html#model-comparison-and-testing"><i class="fa fa-check"></i><b>9.4</b> Model comparison and testing</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="using-lme4-to-fit-mlm-to-longitudinal-data.html"><a href="using-lme4-to-fit-mlm-to-longitudinal-data.html#option-1-using-confidence-intervals"><i class="fa fa-check"></i><b>9.4.1</b> Option 1: using confidence intervals</a></li>
<li class="chapter" data-level="9.4.2" data-path="using-lme4-to-fit-mlm-to-longitudinal-data.html"><a href="using-lme4-to-fit-mlm-to-longitudinal-data.html#tests"><i class="fa fa-check"></i><b>9.4.2</b> Tests</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="using-lme4-to-fit-mlm-to-longitudinal-data.html"><a href="using-lme4-to-fit-mlm-to-longitudinal-data.html#quadratic-model-with-lmer"><i class="fa fa-check"></i><b>9.5</b> Quadratic model with lmer</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="using-lme4-to-fit-mlm-to-longitudinal-data.html"><a href="using-lme4-to-fit-mlm-to-longitudinal-data.html#a-note-on-quadratic-terms"><i class="fa fa-check"></i><b>9.5.1</b> A note on quadratic terms</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="using-lme4-to-fit-mlm-to-longitudinal-data.html"><a href="using-lme4-to-fit-mlm-to-longitudinal-data.html#summary-of-the-sleepstudy-analysis"><i class="fa fa-check"></i><b>9.6</b> Summary of the sleepstudy analysis</a></li>
<li class="chapter" data-level="9.7" data-path="using-lme4-to-fit-mlm-to-longitudinal-data.html"><a href="using-lme4-to-fit-mlm-to-longitudinal-data.html#preview-of-the-blackmore-data-used-for-assignment-7b"><i class="fa fa-check"></i><b>9.7</b> Preview of the Blackmore data used for Assignment 7b</a>
<ul>
<li class="chapter" data-level="9.7.1" data-path="using-lme4-to-fit-mlm-to-longitudinal-data.html"><a href="using-lme4-to-fit-mlm-to-longitudinal-data.html#a-note-on-the-age-variable-in-blackmore"><i class="fa fa-check"></i><b>9.7.1</b> A note on the age variable in Blackmore</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="longitudinal-models-with-upper-level-predictors.html"><a href="longitudinal-models-with-upper-level-predictors.html"><i class="fa fa-check"></i><b>10</b> Longitudinal models with upper-level predictors</a>
<ul>
<li class="chapter" data-level="10.1" data-path="longitudinal-models-with-upper-level-predictors.html"><a href="longitudinal-models-with-upper-level-predictors.html#overview-2"><i class="fa fa-check"></i><b>10.1</b> Overview</a></li>
<li class="chapter" data-level="10.2" data-path="longitudinal-models-with-upper-level-predictors.html"><a href="longitudinal-models-with-upper-level-predictors.html#part-1-intercepts-and-slopes-as-outcomes"><i class="fa fa-check"></i><b>10.2</b> Part 1: Intercepts and Slopes as Outcomes</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="longitudinal-models-with-upper-level-predictors.html"><a href="longitudinal-models-with-upper-level-predictors.html#a-short-tutorial-on-ggplot2"><i class="fa fa-check"></i><b>10.2.1</b> A short tutorial on ggplot2</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="longitudinal-models-with-upper-level-predictors.html"><a href="longitudinal-models-with-upper-level-predictors.html#adding-level-2-predictors"><i class="fa fa-check"></i><b>10.3</b> Adding level 2 predictors</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="longitudinal-models-with-upper-level-predictors.html"><a href="longitudinal-models-with-upper-level-predictors.html#transforming-the-exercise-variable"><i class="fa fa-check"></i><b>10.3.1</b> Transforming the Exercise Variable</a></li>
<li class="chapter" data-level="10.3.2" data-path="longitudinal-models-with-upper-level-predictors.html"><a href="longitudinal-models-with-upper-level-predictors.html#steps-1-and-2"><i class="fa fa-check"></i><b>10.3.2</b> Steps 1 and 2:</a></li>
<li class="chapter" data-level="10.3.3" data-path="longitudinal-models-with-upper-level-predictors.html"><a href="longitudinal-models-with-upper-level-predictors.html#step-3"><i class="fa fa-check"></i><b>10.3.3</b> Step 3:</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="longitudinal-models-with-upper-level-predictors.html"><a href="longitudinal-models-with-upper-level-predictors.html#summary-1"><i class="fa fa-check"></i><b>10.4</b> Summary</a></li>
<li class="chapter" data-level="10.5" data-path="longitudinal-models-with-upper-level-predictors.html"><a href="longitudinal-models-with-upper-level-predictors.html#adding-level-2-explanatory-variables"><i class="fa fa-check"></i><b>10.5</b> Adding Level-2 Explanatory variables</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="longitudinal-models-with-upper-level-predictors.html"><a href="longitudinal-models-with-upper-level-predictors.html#visualizing-the-transformed-data"><i class="fa fa-check"></i><b>10.5.1</b> Visualizing the transformed data</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="longitudinal-models-with-upper-level-predictors.html"><a href="longitudinal-models-with-upper-level-predictors.html#time-dependent-covariates"><i class="fa fa-check"></i><b>10.6</b> Time dependent covariates</a>
<ul>
<li class="chapter" data-level="10.6.1" data-path="longitudinal-models-with-upper-level-predictors.html"><a href="longitudinal-models-with-upper-level-predictors.html#level-1-time-dependent-sports-predictor"><i class="fa fa-check"></i><b>10.6.1</b> Level-1: Time-dependent sports predictor</a></li>
<li class="chapter" data-level="10.6.2" data-path="longitudinal-models-with-upper-level-predictors.html"><a href="longitudinal-models-with-upper-level-predictors.html#level-2-participant-level-indicator-of-sports-participation"><i class="fa fa-check"></i><b>10.6.2</b> Level-2: Participant-level indicator of sports participation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="multilevel-logistic-regression.html"><a href="multilevel-logistic-regression.html"><i class="fa fa-check"></i><b>11</b> Multilevel logistic regression</a>
<ul>
<li class="chapter" data-level="11.1" data-path="multilevel-logistic-regression.html"><a href="multilevel-logistic-regression.html#unconditional-model"><i class="fa fa-check"></i><b>11.1</b> Unconditional model</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="multilevel-logistic-regression.html"><a href="multilevel-logistic-regression.html#fitting-the-model"><i class="fa fa-check"></i><b>11.1.1</b> Fitting the model</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="multilevel-logistic-regression.html"><a href="multilevel-logistic-regression.html#conditional-model"><i class="fa fa-check"></i><b>11.2</b> Conditional model</a></li>
<li class="chapter" data-level="11.3" data-path="multilevel-logistic-regression.html"><a href="multilevel-logistic-regression.html#interpreting-odds-ratios"><i class="fa fa-check"></i><b>11.3</b> Interpreting odds ratios</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="mlm-v.-gee-for-binary-outcomes.html"><a href="mlm-v.-gee-for-binary-outcomes.html"><i class="fa fa-check"></i><b>12</b> MLM v. GEE for Binary Outcomes</a>
<ul>
<li class="chapter" data-level="12.1" data-path="mlm-v.-gee-for-binary-outcomes.html"><a href="mlm-v.-gee-for-binary-outcomes.html#overview-3"><i class="fa fa-check"></i><b>12.1</b> Overview</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="mlm-v.-gee-for-binary-outcomes.html"><a href="mlm-v.-gee-for-binary-outcomes.html#dataset"><i class="fa fa-check"></i><b>12.1.1</b> Dataset</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="mlm-v.-gee-for-binary-outcomes.html"><a href="mlm-v.-gee-for-binary-outcomes.html#hlm-model"><i class="fa fa-check"></i><b>12.2</b> HLM Model</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="mlm-v.-gee-for-binary-outcomes.html"><a href="mlm-v.-gee-for-binary-outcomes.html#interpreting-odds-ratios-1"><i class="fa fa-check"></i><b>12.2.1</b> Interpreting odds ratios</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="mlm-v.-gee-for-binary-outcomes.html"><a href="mlm-v.-gee-for-binary-outcomes.html#population-average-model-with-gee"><i class="fa fa-check"></i><b>12.3</b> Population Average Model with GEE</a></li>
<li class="chapter" data-level="12.4" data-path="mlm-v.-gee-for-binary-outcomes.html"><a href="mlm-v.-gee-for-binary-outcomes.html#hlm-with-level-2-predictors"><i class="fa fa-check"></i><b>12.4</b> HLM with level-2 predictors</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="mlm-v.-gee-for-binary-outcomes.html"><a href="mlm-v.-gee-for-binary-outcomes.html#random-slopes-1"><i class="fa fa-check"></i><b>12.4.1</b> Random slopes</a></li>
<li class="chapter" data-level="12.4.2" data-path="mlm-v.-gee-for-binary-outcomes.html"><a href="mlm-v.-gee-for-binary-outcomes.html#level-2-predictors"><i class="fa fa-check"></i><b>12.4.2</b> Level 2 predictors</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="mlm-v.-gee-for-binary-outcomes.html"><a href="mlm-v.-gee-for-binary-outcomes.html#compare-to-gee"><i class="fa fa-check"></i><b>12.5</b> Compare to GEE</a>
<ul>
<li class="chapter" data-level="12.5.1" data-path="mlm-v.-gee-for-binary-outcomes.html"><a href="mlm-v.-gee-for-binary-outcomes.html#visualizing-res"><i class="fa fa-check"></i><b>12.5.1</b> Visualizing REs</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Generalized Linear Mixed Models with R: A tutorial</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="regression-with-counts-as-outcomes" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">4</span> Regression with Counts as Outcomes<a href="regression-with-counts-as-outcomes.html#regression-with-counts-as-outcomes" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>As a reminder from the text, unlike the log-odds used as the link in logistic regression, the standard “log-linear” model uses the natural logarithm (<span class="math inline">\(\log (x)\)</span>) as the link function so:</p>
<p><span class="math display">\[
\log{[\hat{\mu}(\textbf{x})]} = \beta_{0}+\beta_{1}x_{1} + \ldots
\]</span></p>
<p>We use the notation <span class="math inline">\(\hat{\mu}(\textbf{x})\)</span> as the expected value of <span class="math inline">\(y\)</span> given <span class="math inline">\(\textbf{x}\)</span></p>
<p>Interpretation of coefficients:</p>
<ul>
<li>Log scale: an increase of 1 unit of <span class="math inline">\(x_i\)</span> leads to <span class="math inline">\(\beta_{i}\)</span> increase or decrease in <span class="math inline">\(\log[\hat{\mu}]\)</span>
<ul>
<li>with other variables in the model, this is an <strong>adjusted</strong> change</li>
</ul></li>
<li>Exponentiated: an increase of 1 unit of <span class="math inline">\(x_i\)</span> leads to <span class="math inline">\(e^{\beta_{i}}\)</span> times the number or rate of <span class="math inline">\(Y\)</span>
<ul>
<li>again, this will be an <strong>adjusted</strong> change in multiple regression</li>
</ul></li>
</ul>
<div id="example-data-phmc-fruits-question" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Example data: PHMC Fruits question<a href="regression-with-counts-as-outcomes.html#example-data-phmc-fruits-question" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In 2018, the <a href="https://research.phmc.org/">Public Health Management Corporation</a> conducted a home health survey sampling residents of the southeastern PA region (Bucks, Montgomery, Chester, Delaware, and Philadelphia Counties).</p>
<p>One question they asked was:</p>
<blockquote>
<p>How many servings of fruits and vegetables do you eat on a typical day?</p>
</blockquote>
<p>Responses were recorded as integers: <span class="math inline">\(y=\{0, \dots, 15\}\)</span></p>
<p>Here’s a histogram of the responses</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="regression-with-counts-as-outcomes.html#cb133-1" tabindex="-1"></a>d <span class="ot">&lt;-</span> foreign<span class="sc">::</span><span class="fu">read.spss</span>(<span class="st">&quot;https://rickhass.github.io/PHMC_count_tutorial_2.sav?raw=true&quot;</span>, <span class="at">to.data.frame =</span> T)</span>
<span id="cb133-2"><a href="regression-with-counts-as-outcomes.html#cb133-2" tabindex="-1"></a></span>
<span id="cb133-3"><a href="regression-with-counts-as-outcomes.html#cb133-3" tabindex="-1"></a><span class="fu">hist</span>(d<span class="sc">$</span>FRUITS,  <span class="at">breaks =</span> <span class="dv">12</span>, <span class="at">main =</span> <span class="st">&quot;&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;Number of Fruits&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Freq&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/fruits1-1.png" width="672" /></p>
<p>Since we do have a numeric, possibly unbounded count, but not a lot of zeros, we’ll try an ordinary linear model with <code>lm()</code></p>
<p>We’ll use the following predictors:</p>
<ol style="list-style-type: decimal">
<li>Whether or not the person has insurance</li>
<li>Their biological sex</li>
<li>Their BMI</li>
</ol>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="regression-with-counts-as-outcomes.html#cb134-1" tabindex="-1"></a>lm.fruit <span class="ot">&lt;-</span> <span class="fu">lm</span>(FRUITS <span class="sc">~</span> INSUREDA2 <span class="sc">+</span> SEX01 <span class="sc">+</span> BMI, <span class="at">data=</span>d)</span>
<span id="cb134-2"><a href="regression-with-counts-as-outcomes.html#cb134-2" tabindex="-1"></a><span class="fu">summary</span>(lm.fruit)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = FRUITS ~ INSUREDA2 + SEX01 + BMI, data = d)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.9551 -1.1369 -0.3328  0.6685  8.7147 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  2.623202   0.167370  15.673  &lt; 2e-16 ***
## INSUREDA2No -0.222155   0.146952  -1.512   0.1307    
## SEX01Female  0.473712   0.071179   6.655 3.61e-11 ***
## BMI         -0.009467   0.005611  -1.687   0.0917 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.598 on 2081 degrees of freedom
##   (173 observations deleted due to missingness)
## Multiple R-squared:  0.02356,    Adjusted R-squared:  0.02215 
## F-statistic: 16.74 on 3 and 2081 DF,  p-value: 9.586e-11</code></pre>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="regression-with-counts-as-outcomes.html#cb136-1" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">residuals</span>(lm.fruit))</span></code></pre></div>
<p><img src="_main_files/figure-html/fruits_lm-1.png" width="672" /></p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="regression-with-counts-as-outcomes.html#cb137-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">fitted.values</span>(lm.fruit), <span class="fu">residuals</span>(lm.fruit), <span class="at">xlab =</span> <span class="st">&quot;Predicted value&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Residual&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/fruits_lm-2.png" width="672" /></p>
<p>As we can see, the residuals are not normally distributed, and their variance is not constant. Perhaps we can do better with a Poisson model.</p>
</div>
<div id="coefficients-in-poisson-models" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Coefficients in Poisson Models<a href="regression-with-counts-as-outcomes.html#coefficients-in-poisson-models" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="regression-with-counts-as-outcomes.html#cb138-1" tabindex="-1"></a>glm.fruit <span class="ot">&lt;-</span> <span class="fu">glm</span>(FRUITS <span class="sc">~</span> INSUREDA2 <span class="sc">+</span> SEX01 <span class="sc">+</span> BMI, <span class="at">family =</span> <span class="st">&quot;poisson&quot;</span>, <span class="at">data=</span>d)</span>
<span id="cb138-2"><a href="regression-with-counts-as-outcomes.html#cb138-2" tabindex="-1"></a><span class="fu">summary</span>(glm.fruit)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = FRUITS ~ INSUREDA2 + SEX01 + BMI, family = &quot;poisson&quot;, 
##     data = d)
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  0.957420   0.065044  14.720  &lt; 2e-16 ***
## INSUREDA2No -0.088984   0.059421  -1.498   0.1343    
## SEX01Female  0.184059   0.028081   6.555 5.58e-11 ***
## BMI         -0.003588   0.002175  -1.649   0.0991 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 1979.1  on 2084  degrees of freedom
## Residual deviance: 1929.6  on 2081  degrees of freedom
##   (173 observations deleted due to missingness)
## AIC: 7525.7
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="regression-with-counts-as-outcomes.html#cb140-1" tabindex="-1"></a><span class="fu">halfnorm</span>(<span class="fu">residuals</span>(glm.fruit))</span></code></pre></div>
<p><img src="_main_files/figure-html/plot_resid-1.png" width="672" /></p>
<p>It looks like we may have some outliers, but we’ll proceed with interpreting coefficients before looking into the model fit.</p>
<div id="exponentiated-coefficients-interpretation" class="section level3 hasAnchor" number="4.2.1">
<h3><span class="header-section-number">4.2.1</span> Exponentiated Coefficients Interpretation<a href="regression-with-counts-as-outcomes.html#exponentiated-coefficients-interpretation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A good source for interpretation of Poisson coefficients is here: <a href="https://stats.idre.ucla.edu/r/dae/poisson-regression/" class="uri">https://stats.idre.ucla.edu/r/dae/poisson-regression/</a></p>
<ul>
<li>When we exponentiate, we get incidence rates, which are essentially expected counts.
Let’s look at the indicator for <code>Female</code>: the raw coefficient is <span class="math inline">\(\hat{\beta} = 0.184\)</span> meaning that, on average, females eat 0.184 more <strong>log</strong> fruits compared with males.</li>
</ul>
<p>Let’s compare with the exponentiated coefficient: the IRR</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="regression-with-counts-as-outcomes.html#cb141-1" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(glm.fruit))</span></code></pre></div>
<pre><code>## (Intercept) INSUREDA2No SEX01Female         BMI 
##   2.6049669   0.9148600   1.2020871   0.9964187</code></pre>
<p>So <span class="math inline">\(e^{\beta} = 1.202\)</span> meaning that females eat about <span class="math inline">\(20\%\)</span> more fruit on average. Or that the number of fruits consumed by the average female is <span class="math inline">\(1.20\)</span> times that eaten by males.</p>
<p>As with logistic regression, we can exponentiate the confidence limits to get CI’s for the incidence rate ratios:</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="regression-with-counts-as-outcomes.html#cb143-1" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">cbind</span>(<span class="fu">exp</span>(<span class="fu">coef</span>(glm.fruit)), <span class="fu">exp</span>(<span class="fu">confint</span>(glm.fruit))), <span class="dv">3</span>)</span></code></pre></div>
<pre><code>## Waiting for profiling to be done...</code></pre>
<pre><code>##                   2.5 % 97.5 %
## (Intercept) 2.605 2.294  2.960
## INSUREDA2No 0.915 0.813  1.026
## SEX01Female 1.202 1.138  1.270
## BMI         0.996 0.992  1.001</code></pre>
</div>
</div>
<div id="overdispersion-and-other-count-regression-models" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Overdispersion and other count regression models<a href="regression-with-counts-as-outcomes.html#overdispersion-and-other-count-regression-models" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>As we see above, the dispersion parameter is taken to be equal to 1. We can relax that assumption and estimate it using the <code>quasipoisson</code> family.</p>
<ul>
<li>The Poisson model assumes that the dispersion parameter, <span class="math inline">\(\phi\)</span> is equal to 1 in the below equation</li>
</ul>
<p><span class="math display">\[
Var(y \mid \textbf{x}) = \phi \times V[\mu(\textbf{x})]
\]</span></p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="regression-with-counts-as-outcomes.html#cb146-1" tabindex="-1"></a>qp.fruit <span class="ot">&lt;-</span> <span class="fu">glm</span>(FRUITS <span class="sc">~</span> INSUREDA2 <span class="sc">+</span> SEX01 <span class="sc">+</span> BMI, <span class="at">family =</span> quasipoisson, <span class="at">data=</span>d)</span>
<span id="cb146-2"><a href="regression-with-counts-as-outcomes.html#cb146-2" tabindex="-1"></a><span class="fu">summary</span>(qp.fruit)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = FRUITS ~ INSUREDA2 + SEX01 + BMI, family = quasipoisson, 
##     data = d)
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.957420   0.064138  14.928  &lt; 2e-16 ***
## INSUREDA2No -0.088984   0.058593  -1.519   0.1290    
## SEX01Female  0.184059   0.027689   6.647  3.8e-11 ***
## BMI         -0.003588   0.002145  -1.673   0.0946 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for quasipoisson family taken to be 0.9723222)
## 
##     Null deviance: 1979.1  on 2084  degrees of freedom
## Residual deviance: 1929.6  on 2081  degrees of freedom
##   (173 observations deleted due to missingness)
## AIC: NA
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>Here, we see that <span class="math inline">\(\hat{\phi} = 0.972\)</span>, so the original fit is likely to be ok. Indeed, we can test it’s fit directly by getting a p-value for the residual deviance of the original model:</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="regression-with-counts-as-outcomes.html#cb148-1" tabindex="-1"></a><span class="fu">with</span>(glm.fruit, <span class="fu">cbind</span>(<span class="at">res.deviance =</span> deviance, <span class="at">df =</span> df.residual,</span>
<span id="cb148-2"><a href="regression-with-counts-as-outcomes.html#cb148-2" tabindex="-1"></a>  <span class="at">p =</span> <span class="fu">pchisq</span>(deviance, df.residual, <span class="at">lower.tail=</span><span class="cn">FALSE</span>)))</span></code></pre></div>
<pre><code>##      res.deviance   df         p
## [1,]     1929.629 2081 0.9916986</code></pre>
<div id="overdispersion-and-zero-inflation" class="section level3 hasAnchor" number="4.3.1">
<h3><span class="header-section-number">4.3.1</span> Overdispersion and Zero-inflation<a href="regression-with-counts-as-outcomes.html#overdispersion-and-zero-inflation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For an example of overdispersed and zero-inflated data, let’s have a look at a snippet of data collected by Jefferson Health on a number of questions on patients’ health related social needs. To protect PHI, the individual questions are not here, only the number of needs each patient reported (from zero to 8).</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="regression-with-counts-as-outcomes.html#cb150-1" tabindex="-1"></a><span class="fu">load</span>(<span class="fu">url</span>(<span class="st">&quot;https://rickhass.github.io/HRSN.RData?raw=true&quot;</span>))</span>
<span id="cb150-2"><a href="regression-with-counts-as-outcomes.html#cb150-2" tabindex="-1"></a></span>
<span id="cb150-3"><a href="regression-with-counts-as-outcomes.html#cb150-3" tabindex="-1"></a><span class="fu">summary</span>(HRSN.example)</span></code></pre></div>
<pre><code>##      Sex                Age                 race4                   SVI4         SumScore     
##  Female:5910   19-44      :3476   White        :6666   1 - Low        :3378   Min.   :0.0000  
##  Male  :4090   45-64      :3274   BlackAA      :1872   2 - Low Medium :2678   1st Qu.:0.0000  
##                65-84      :2963   Asian        : 600   3 - Medium High:1800   Median :0.0000  
##                85 And Over: 287   Other/Unknown: 862   4 - High       :1371   Mean   :0.2177  
##                                                        NA&#39;s           : 773   3rd Qu.:0.0000  
##                                                                               Max.   :8.0000  
##     race3          
##  Length:10000      
##  Class :character  
##  Mode  :character  
##                    
##                    
## </code></pre>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="regression-with-counts-as-outcomes.html#cb152-1" tabindex="-1"></a><span class="fu">xtabs</span>(<span class="sc">~</span>SumScore, <span class="at">data =</span> HRSN.example)</span></code></pre></div>
<pre><code>## SumScore
##    0    1    2    3    4    5    6    7    8 
## 8786  723  250  109   70   38   13    9    2</code></pre>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="regression-with-counts-as-outcomes.html#cb154-1" tabindex="-1"></a><span class="fu">mean</span>(HRSN.example<span class="sc">$</span>SumScore)</span></code></pre></div>
<pre><code>## [1] 0.2177</code></pre>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="regression-with-counts-as-outcomes.html#cb156-1" tabindex="-1"></a><span class="fu">var</span>(HRSN.example<span class="sc">$</span>SumScore)</span></code></pre></div>
<pre><code>## [1] 0.5337601</code></pre>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="regression-with-counts-as-outcomes.html#cb158-1" tabindex="-1"></a><span class="fu">hist</span>(HRSN.example<span class="sc">$</span>SumScore, <span class="at">breaks =</span> <span class="dv">10</span>, <span class="at">xlab =</span> <span class="st">&quot;HRSN&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/hist.hrsn-1.png" width="672" /></p>
<p>So we can see that <span class="math inline">\(\text{Var}(Y) &gt; E(Y)\)</span> in this case.</p>
<p>First, let’s look at a negative binomial regression model, this ignores the fact that about <span class="math inline">\(88\%\)</span> of patients have no needs…</p>
<p>Remember:</p>
<ul>
<li>NB regression will often have very similar coefficients to Poisson</li>
<li>Standard errors will be larger for NB regression, if <span class="math inline">\(\phi &gt; 1\)</span></li>
<li>If overdispersion is the “truth” the SEs for NB regression will be less biased</li>
</ul>
<p>Interpretation of <span class="math inline">\(e^{\beta}\)</span> is the same in NB and Poisson regression</p>
<p>We use the <code>glm.nb</code> function from the <code>MASS</code> package. The syntax is the same as before, and we don’t have to specify a <code>family</code> because the function just fits NB models.</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="regression-with-counts-as-outcomes.html#cb159-1" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb159-2"><a href="regression-with-counts-as-outcomes.html#cb159-2" tabindex="-1"></a></span>
<span id="cb159-3"><a href="regression-with-counts-as-outcomes.html#cb159-3" tabindex="-1"></a>hrsn.nb <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(SumScore <span class="sc">~</span> Sex <span class="sc">+</span> Age <span class="sc">+</span> SVI4 <span class="sc">+</span> race3, <span class="at">data =</span> HRSN.example)</span>
<span id="cb159-4"><a href="regression-with-counts-as-outcomes.html#cb159-4" tabindex="-1"></a><span class="fu">summary</span>(hrsn.nb)</span></code></pre></div>
<pre><code>## 
## Call:
## glm.nb(formula = SumScore ~ Sex + Age + SVI4 + race3, data = HRSN.example, 
##     init.theta = 0.1689023943, link = log)
## 
## Coefficients:
##                     Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)         -1.22624    0.11726 -10.458  &lt; 2e-16 ***
## SexMale             -0.18436    0.07389  -2.495 0.012590 *  
## Age45-64            -0.22775    0.08254  -2.759 0.005794 ** 
## Age65-84            -0.80505    0.09405  -8.560  &lt; 2e-16 ***
## Age85 And Over      -0.90897    0.25519  -3.562 0.000368 ***
## SVI42 - Low Medium   0.40764    0.09397   4.338 1.44e-05 ***
## SVI43 - Medium High  0.57892    0.10308   5.616 1.95e-08 ***
## SVI44 - High         0.92585    0.11327   8.174 2.98e-16 ***
## race3Other          -0.49160    0.11768  -4.177 2.95e-05 ***
## race3White          -0.57691    0.09381  -6.150 7.76e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for Negative Binomial(0.1689) family taken to be 1)
## 
##     Null deviance: 3639.7  on 9226  degrees of freedom
## Residual deviance: 3322.3  on 9217  degrees of freedom
##   (773 observations deleted due to missingness)
## AIC: 9155.1
## 
## Number of Fisher Scoring iterations: 1
## 
## 
##               Theta:  0.16890 
##           Std. Err.:  0.00953 
## 
##  2 x log-likelihood:  -9133.06500</code></pre>
<p>This suggests there is actually **under*-dispersion. This is not exactly true. The issue is that there are very many more zeros than there ought to be given the model.</p>
</div>
</div>
<div id="zero-inflated-models" class="section level2 hasAnchor" number="4.4">
<h2><span class="header-section-number">4.4</span> Zero-inflated models<a href="regression-with-counts-as-outcomes.html#zero-inflated-models" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Remember, Zero-inflated models are <em>Mixture Models</em></p>
<ul>
<li>Mixture distribution is built out of combinations of other distributions</li>
</ul>
<p>In Zero-inflated Models we model separate distributions for “zero v. not zero” and then the counts <span class="math inline">\(1\)</span> to <span class="math inline">\(\inf\)</span></p>
<p><span class="math display">\[
P(Y = 0) \sim Logistic
\]</span>
<span class="math display">\[
P(Y = y_{i}) \sim Count
\]</span></p>
<p>Where “Count” is either Poisson or Negative Binomial</p>
<ul>
<li>Technically, each has a “mixture” proportion, but we’ll ignore that</li>
</ul>
<p>Fitting a Zero-Inflated Negative Binomial (ZINB) model requires the <code>pscl</code> package</p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="regression-with-counts-as-outcomes.html#cb161-1" tabindex="-1"></a><span class="fu">library</span>(pscl)</span></code></pre></div>
<pre><code>## Classes and Methods for R originally developed in the
## Political Science Computational Laboratory
## Department of Political Science
## Stanford University (2002-2015),
## by and under the direction of Simon Jackman.
## hurdle and zeroinfl functions by Achim Zeileis.</code></pre>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="regression-with-counts-as-outcomes.html#cb163-1" tabindex="-1"></a>ZINB<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">zeroinfl</span>(SumScore <span class="sc">~</span> Sex <span class="sc">+</span> race3 <span class="sc">+</span> SVI4 <span class="sc">|</span> SVI4 <span class="sc">+</span> Sex,</span>
<span id="cb163-2"><a href="regression-with-counts-as-outcomes.html#cb163-2" tabindex="-1"></a>  <span class="at">data =</span> HRSN.example, <span class="at">dist =</span> <span class="st">&quot;negbin&quot;</span>)</span>
<span id="cb163-3"><a href="regression-with-counts-as-outcomes.html#cb163-3" tabindex="-1"></a></span>
<span id="cb163-4"><a href="regression-with-counts-as-outcomes.html#cb163-4" tabindex="-1"></a><span class="fu">summary</span>(ZINB<span class="fl">.1</span>)</span></code></pre></div>
<pre><code>## 
## Call:
## zeroinfl(formula = SumScore ~ Sex + race3 + SVI4 | SVI4 + Sex, data = HRSN.example, dist = &quot;negbin&quot;)
## 
## Pearson residuals:
##     Min      1Q  Median      3Q     Max 
## -0.4224 -0.3173 -0.2721 -0.2198 17.5424 
## 
## Count model coefficients (negbin with log link):
##                     Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)         -0.39269    0.24793  -1.584 0.113230    
## SexMale              0.12044    0.10722   1.123 0.261302    
## race3Other          -0.41252    0.11255  -3.665 0.000247 ***
## race3White          -0.58888    0.08957  -6.575 4.88e-11 ***
## SVI42 - Low Medium  -0.01276    0.14831  -0.086 0.931425    
## SVI43 - Medium High  0.27838    0.15436   1.803 0.071315 .  
## SVI44 - High         0.31952    0.15006   2.129 0.033225 *  
## Log(theta)          -0.64406    0.36460  -1.767 0.077312 .  
## 
## Zero-inflation model coefficients (binomial with logit link):
##                     Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)           0.7370     0.3650   2.019  0.04349 *  
## SVI42 - Low Medium   -0.6833     0.2101  -3.253  0.00114 ** 
## SVI43 - Medium High  -0.5381     0.1954  -2.754  0.00588 ** 
## SVI44 - High         -1.1535     0.2572  -4.485 7.29e-06 ***
## SexMale               0.4981     0.1602   3.110  0.00187 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1 
## 
## Theta = 0.5252 
## Number of iterations in BFGS optimization: 45 
## Log-likelihood: -4587 on 13 Df</code></pre>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="regression-with-counts-as-outcomes.html#cb165-1" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">cbind</span>(<span class="fu">coef</span>(ZINB<span class="fl">.1</span>), <span class="fu">confint</span>(ZINB<span class="fl">.1</span>)))</span></code></pre></div>
<pre><code>##                                         2.5 %    97.5 %
## count_(Intercept)         0.6752389 0.4153512 1.0977399
## count_SexMale             1.1279935 0.9142019 1.3917816
## count_race3Other          0.6619785 0.5309322 0.8253701
## count_race3White          0.5549508 0.4656012 0.6614467
## count_SVI42 - Low Medium  0.9873187 0.7382721 1.3203780
## count_SVI43 - Medium High 1.3209873 0.9761330 1.7876738
## count_SVI44 - High        1.3764721 1.0257433 1.8471244
## zero_(Intercept)          2.0896773 1.0217890 4.2736331
## zero_SVI42 - Low Medium   0.5049381 0.3345206 0.7621729
## zero_SVI43 - Medium High  0.5838432 0.3980924 0.8562656
## zero_SVI44 - High         0.3155179 0.1905896 0.5223345
## zero_SexMale              1.6456525 1.2023081 2.2524778</code></pre>
<p>The strange part is that the Zero-inflation model is a logistic model for a zero count. So we see that compared to low SVI, those in high SVI neighborhoods had <strong>smaller</strong> odds of NOT having an needs.</p>
<p>The count part of the model can be interpreted the same way as ordinary Poisson or NB regression:</p>
<ul>
<li>log count raw coefficient</li>
<li>IRR for the exponentiated coefficient</li>
</ul>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="logistic-regression.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="model-fit-and-assumptions-for-glms.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
