<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>6 Introducing mixed-models and the lme4 package | Generalized Linear Mixed Models with R: A tutorial</title>
  <meta name="description" content="6 Introducing mixed-models and the lme4 package | Generalized Linear Mixed Models with R: A tutorial" />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="6 Introducing mixed-models and the lme4 package | Generalized Linear Mixed Models with R: A tutorial" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="6 Introducing mixed-models and the lme4 package | Generalized Linear Mixed Models with R: A tutorial" />
  
  
  

<meta name="author" content="Rick Hass" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="model-fit-and-assumptions-for-glms.html"/>
<link rel="next" href="mixed-models-as-hierarchical-linear-models.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Overview</a></li>
<li class="chapter" data-level="1" data-path="r-basics.html"><a href="r-basics.html"><i class="fa fa-check"></i><b>1</b> R Basics</a>
<ul>
<li class="chapter" data-level="1.1" data-path="r-basics.html"><a href="r-basics.html#what-is-coding"><i class="fa fa-check"></i><b>1.1</b> What is “coding”</a></li>
<li class="chapter" data-level="1.2" data-path="r-basics.html"><a href="r-basics.html#r-console-versus-the-rstudio-script"><i class="fa fa-check"></i><b>1.2</b> R Console versus the RStudio Script</a></li>
<li class="chapter" data-level="1.3" data-path="r-basics.html"><a href="r-basics.html#working-with-data"><i class="fa fa-check"></i><b>1.3</b> Working with data</a></li>
<li class="chapter" data-level="1.4" data-path="r-basics.html"><a href="r-basics.html#using-a-script-to-generate-data-and-computing-the-mean-and-standard-deviation"><i class="fa fa-check"></i><b>1.4</b> Using a script to generate data, and computing the mean and standard deviation</a></li>
<li class="chapter" data-level="1.5" data-path="r-basics.html"><a href="r-basics.html#importing-data"><i class="fa fa-check"></i><b>1.5</b> Importing Data</a></li>
<li class="chapter" data-level="1.6" data-path="r-basics.html"><a href="r-basics.html#reading-in-an-spss-file"><i class="fa fa-check"></i><b>1.6</b> Reading in an SPSS file</a>
<ul>
<li class="chapter" data-level="1.6.1" data-path="r-basics.html"><a href="r-basics.html#a-quick-note-on-indexing"><i class="fa fa-check"></i><b>1.6.1</b> A quick note on indexing</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="r-basics.html"><a href="r-basics.html#frequencies-and-contingency-tables"><i class="fa fa-check"></i><b>1.7</b> Frequencies and Contingency Tables</a></li>
<li class="chapter" data-level="1.8" data-path="r-basics.html"><a href="r-basics.html#descriptive-statistics"><i class="fa fa-check"></i><b>1.8</b> Descriptive statistics</a>
<ul>
<li class="chapter" data-level="1.8.1" data-path="r-basics.html"><a href="r-basics.html#the-describe-function"><i class="fa fa-check"></i><b>1.8.1</b> The describe function</a></li>
<li class="chapter" data-level="1.8.2" data-path="r-basics.html"><a href="r-basics.html#the-describeby-function"><i class="fa fa-check"></i><b>1.8.2</b> The describeBy function</a></li>
<li class="chapter" data-level="1.8.3" data-path="r-basics.html"><a href="r-basics.html#computing-a-new-variable-and-adding-it-to-the-dataframe"><i class="fa fa-check"></i><b>1.8.3</b> Computing a new variable and adding it to the dataframe</a></li>
</ul></li>
<li class="chapter" data-level="1.9" data-path="r-basics.html"><a href="r-basics.html#visualizing-data"><i class="fa fa-check"></i><b>1.9</b> Visualizing Data</a>
<ul>
<li class="chapter" data-level="1.9.1" data-path="r-basics.html"><a href="r-basics.html#histograms-and-density-plots"><i class="fa fa-check"></i><b>1.9.1</b> Histograms and density plots</a></li>
<li class="chapter" data-level="1.9.2" data-path="r-basics.html"><a href="r-basics.html#boxplots"><i class="fa fa-check"></i><b>1.9.2</b> Boxplots</a></li>
<li class="chapter" data-level="1.9.3" data-path="r-basics.html"><a href="r-basics.html#scatterplots"><i class="fa fa-check"></i><b>1.9.3</b> Scatterplots</a></li>
</ul></li>
<li class="chapter" data-level="1.10" data-path="r-basics.html"><a href="r-basics.html#review"><i class="fa fa-check"></i><b>1.10</b> Review</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="ordinary-linear-regression.html"><a href="ordinary-linear-regression.html"><i class="fa fa-check"></i><b>2</b> Ordinary Linear Regression</a>
<ul>
<li class="chapter" data-level="2.1" data-path="ordinary-linear-regression.html"><a href="ordinary-linear-regression.html#our-data"><i class="fa fa-check"></i><b>2.1</b> Our data</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="ordinary-linear-regression.html"><a href="ordinary-linear-regression.html#converting-from-numeric-to-factor"><i class="fa fa-check"></i><b>2.1.1</b> Converting from numeric to factor</a></li>
<li class="chapter" data-level="2.1.2" data-path="ordinary-linear-regression.html"><a href="ordinary-linear-regression.html#confidence-intervals-v.-p-values"><i class="fa fa-check"></i><b>2.1.2</b> Confidence Intervals v. p-values</a></li>
<li class="chapter" data-level="2.1.3" data-path="ordinary-linear-regression.html"><a href="ordinary-linear-regression.html#adding-interaction-terms"><i class="fa fa-check"></i><b>2.1.3</b> Adding interaction terms</a></li>
<li class="chapter" data-level="2.1.4" data-path="ordinary-linear-regression.html"><a href="ordinary-linear-regression.html#interaction-model-for-gambling"><i class="fa fa-check"></i><b>2.1.4</b> Interaction model for Gambling</a></li>
<li class="chapter" data-level="2.1.5" data-path="ordinary-linear-regression.html"><a href="ordinary-linear-regression.html#interaction-output"><i class="fa fa-check"></i><b>2.1.5</b> Interaction Output</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="ordinary-linear-regression.html"><a href="ordinary-linear-regression.html#anova-and-drop1-commands"><i class="fa fa-check"></i><b>2.2</b> ANOVA and drop1 commands</a></li>
<li class="chapter" data-level="2.3" data-path="ordinary-linear-regression.html"><a href="ordinary-linear-regression.html#plots"><i class="fa fa-check"></i><b>2.3</b> Plots</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>3</b> Logistic Regression</a>
<ul>
<li class="chapter" data-level="3.1" data-path="logistic-regression.html"><a href="logistic-regression.html#an-example-diabetes-risk-factors"><i class="fa fa-check"></i><b>3.1</b> An Example: Diabetes risk factors</a></li>
<li class="chapter" data-level="3.2" data-path="logistic-regression.html"><a href="logistic-regression.html#model-discrimination-and-fit"><i class="fa fa-check"></i><b>3.2</b> Model Discrimination and Fit</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="logistic-regression.html"><a href="logistic-regression.html#roc-and-auroc"><i class="fa fa-check"></i><b>3.2.1</b> ROC and AUROC</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="regression-with-counts-as-outcomes.html"><a href="regression-with-counts-as-outcomes.html"><i class="fa fa-check"></i><b>4</b> Regression with Counts as Outcomes</a>
<ul>
<li class="chapter" data-level="4.1" data-path="regression-with-counts-as-outcomes.html"><a href="regression-with-counts-as-outcomes.html#example-data-phmc-fruits-question"><i class="fa fa-check"></i><b>4.1</b> Example data: PHMC Fruits question</a></li>
<li class="chapter" data-level="4.2" data-path="regression-with-counts-as-outcomes.html"><a href="regression-with-counts-as-outcomes.html#coefficients-in-poisson-models"><i class="fa fa-check"></i><b>4.2</b> Coefficients in Poisson Models</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="regression-with-counts-as-outcomes.html"><a href="regression-with-counts-as-outcomes.html#exponentiated-coefficients-interpretation"><i class="fa fa-check"></i><b>4.2.1</b> Exponentiated Coefficients Interpretation</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="regression-with-counts-as-outcomes.html"><a href="regression-with-counts-as-outcomes.html#overdispersion-and-other-count-regression-models"><i class="fa fa-check"></i><b>4.3</b> Overdispersion and other count regression models</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="regression-with-counts-as-outcomes.html"><a href="regression-with-counts-as-outcomes.html#overdispersion-and-zero-inflation"><i class="fa fa-check"></i><b>4.3.1</b> Overdispersion and Zero-inflation</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="regression-with-counts-as-outcomes.html"><a href="regression-with-counts-as-outcomes.html#zero-inflated-models"><i class="fa fa-check"></i><b>4.4</b> Zero-inflated models</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="model-fit-and-assumptions-for-glms.html"><a href="model-fit-and-assumptions-for-glms.html"><i class="fa fa-check"></i><b>5</b> Model Fit and Assumptions for GLMs</a>
<ul>
<li class="chapter" data-level="5.1" data-path="model-fit-and-assumptions-for-glms.html"><a href="model-fit-and-assumptions-for-glms.html#model-checking-and-diagnostics-in-ordinary-least-squares"><i class="fa fa-check"></i><b>5.1</b> Model Checking and Diagnostics in Ordinary Least Squares</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="model-fit-and-assumptions-for-glms.html"><a href="model-fit-and-assumptions-for-glms.html#residuals-v.-fitted-values"><i class="fa fa-check"></i><b>5.1.1</b> Residuals v. Fitted Values</a></li>
<li class="chapter" data-level="5.1.2" data-path="model-fit-and-assumptions-for-glms.html"><a href="model-fit-and-assumptions-for-glms.html#normalty-of-residuals"><i class="fa fa-check"></i><b>5.1.2</b> Normalty of residuals</a></li>
<li class="chapter" data-level="5.1.3" data-path="model-fit-and-assumptions-for-glms.html"><a href="model-fit-and-assumptions-for-glms.html#leverage"><i class="fa fa-check"></i><b>5.1.3</b> Leverage</a></li>
<li class="chapter" data-level="5.1.4" data-path="model-fit-and-assumptions-for-glms.html"><a href="model-fit-and-assumptions-for-glms.html#influence"><i class="fa fa-check"></i><b>5.1.4</b> Influence</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="model-fit-and-assumptions-for-glms.html"><a href="model-fit-and-assumptions-for-glms.html#model-checking-and-diagnostics-in-logistic-regression"><i class="fa fa-check"></i><b>5.2</b> Model Checking and Diagnostics in Logistic Regression</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="model-fit-and-assumptions-for-glms.html"><a href="model-fit-and-assumptions-for-glms.html#hosmer-lemeshow-test"><i class="fa fa-check"></i><b>5.2.1</b> Hosmer-Lemeshow Test</a></li>
<li class="chapter" data-level="5.2.2" data-path="model-fit-and-assumptions-for-glms.html"><a href="model-fit-and-assumptions-for-glms.html#nagelkerkes-pseudo-r-squared"><i class="fa fa-check"></i><b>5.2.2</b> Nagelkerke’s pseudo R-squared</a></li>
<li class="chapter" data-level="5.2.3" data-path="model-fit-and-assumptions-for-glms.html"><a href="model-fit-and-assumptions-for-glms.html#residuals-and-leverages"><i class="fa fa-check"></i><b>5.2.3</b> Residuals and leverages</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="model-fit-and-assumptions-for-glms.html"><a href="model-fit-and-assumptions-for-glms.html#summary"><i class="fa fa-check"></i><b>5.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="introducing-mixed-models-and-the-lme4-package.html"><a href="introducing-mixed-models-and-the-lme4-package.html"><i class="fa fa-check"></i><b>6</b> Introducing mixed-models and the lme4 package</a>
<ul>
<li class="chapter" data-level="6.1" data-path="introducing-mixed-models-and-the-lme4-package.html"><a href="introducing-mixed-models-and-the-lme4-package.html#options-in-r"><i class="fa fa-check"></i><b>6.1</b> Options in R</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="introducing-mixed-models-and-the-lme4-package.html"><a href="introducing-mixed-models-and-the-lme4-package.html#why-lme4"><i class="fa fa-check"></i><b>6.1.1</b> Why lme4?</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="introducing-mixed-models-and-the-lme4-package.html"><a href="introducing-mixed-models-and-the-lme4-package.html#a-possible-workflow"><i class="fa fa-check"></i><b>6.2</b> A possible workflow</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="introducing-mixed-models-and-the-lme4-package.html"><a href="introducing-mixed-models-and-the-lme4-package.html#high-school-and-beyond"><i class="fa fa-check"></i><b>6.2.1</b> High School and Beyond</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="introducing-mixed-models-and-the-lme4-package.html"><a href="introducing-mixed-models-and-the-lme4-package.html#model-1-one-way-random-effects-anova-using-reml"><i class="fa fa-check"></i><b>6.3</b> Model 1: one-way random-effects ANOVA using REML</a></li>
<li class="chapter" data-level="6.4" data-path="introducing-mixed-models-and-the-lme4-package.html"><a href="introducing-mixed-models-and-the-lme4-package.html#quasi-anova-estimator"><i class="fa fa-check"></i><b>6.4</b> Quasi-ANOVA estimator</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="introducing-mixed-models-and-the-lme4-package.html"><a href="introducing-mixed-models-and-the-lme4-package.html#unrestricted-maximum-likelihood"><i class="fa fa-check"></i><b>6.4.1</b> (unrestricted) Maximum Likelihood</a></li>
<li class="chapter" data-level="6.4.2" data-path="introducing-mixed-models-and-the-lme4-package.html"><a href="introducing-mixed-models-and-the-lme4-package.html#intraclass-correlation"><i class="fa fa-check"></i><b>6.4.2</b> Intraclass correlation</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="introducing-mixed-models-and-the-lme4-package.html"><a href="introducing-mixed-models-and-the-lme4-package.html#bootstrapped-confidence-intervals"><i class="fa fa-check"></i><b>6.5</b> Bootstrapped confidence intervals</a></li>
<li class="chapter" data-level="6.6" data-path="introducing-mixed-models-and-the-lme4-package.html"><a href="introducing-mixed-models-and-the-lme4-package.html#linear-mixed-effects"><i class="fa fa-check"></i><b>6.6</b> Linear mixed-effects</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="introducing-mixed-models-and-the-lme4-package.html"><a href="introducing-mixed-models-and-the-lme4-package.html#random-effects-estimates"><i class="fa fa-check"></i><b>6.6.1</b> Random effects estimates</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="mixed-models-as-hierarchical-linear-models.html"><a href="mixed-models-as-hierarchical-linear-models.html"><i class="fa fa-check"></i><b>7</b> Mixed models as Hierarchical Linear Models</a>
<ul>
<li class="chapter" data-level="7.1" data-path="mixed-models-as-hierarchical-linear-models.html"><a href="mixed-models-as-hierarchical-linear-models.html#high-school-and-beyond-data"><i class="fa fa-check"></i><b>7.1</b> High School and Beyond Data</a></li>
<li class="chapter" data-level="7.2" data-path="mixed-models-as-hierarchical-linear-models.html"><a href="mixed-models-as-hierarchical-linear-models.html#model-1-unconditional-model"><i class="fa fa-check"></i><b>7.2</b> Model 1: unconditional model</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="mixed-models-as-hierarchical-linear-models.html"><a href="mixed-models-as-hierarchical-linear-models.html#unconditional-icc"><i class="fa fa-check"></i><b>7.2.1</b> Unconditional ICC</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="mixed-models-as-hierarchical-linear-models.html"><a href="mixed-models-as-hierarchical-linear-models.html#means-as-outcomes-binary-predictor"><i class="fa fa-check"></i><b>7.3</b> Means as outcomes: Binary Predictor</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="mixed-models-as-hierarchical-linear-models.html"><a href="mixed-models-as-hierarchical-linear-models.html#means-as-outcomes-continuous-predictor"><i class="fa fa-check"></i><b>7.3.1</b> Means as outcomes: continuous predictor</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="mixed-models-as-hierarchical-linear-models.html"><a href="mixed-models-as-hierarchical-linear-models.html#multiple-hierarchical-linear-regression"><i class="fa fa-check"></i><b>7.4</b> Multiple hierarchical linear regression</a></li>
<li class="chapter" data-level="7.5" data-path="mixed-models-as-hierarchical-linear-models.html"><a href="mixed-models-as-hierarchical-linear-models.html#plotting-predictor-effects"><i class="fa fa-check"></i><b>7.5</b> Plotting predictor effects</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="more-on-hierarchical-linear-models.html"><a href="more-on-hierarchical-linear-models.html"><i class="fa fa-check"></i><b>8</b> More on Hierarchical Linear Models</a>
<ul>
<li class="chapter" data-level="8.1" data-path="more-on-hierarchical-linear-models.html"><a href="more-on-hierarchical-linear-models.html#overview-1"><i class="fa fa-check"></i><b>8.1</b> Overview</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="more-on-hierarchical-linear-models.html"><a href="more-on-hierarchical-linear-models.html#load-the-data"><i class="fa fa-check"></i><b>8.1.1</b> Load the data</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="more-on-hierarchical-linear-models.html"><a href="more-on-hierarchical-linear-models.html#random-coefficients-model"><i class="fa fa-check"></i><b>8.2</b> Random Coefficients model</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="more-on-hierarchical-linear-models.html"><a href="more-on-hierarchical-linear-models.html#visualizing-the-within-school-slopes"><i class="fa fa-check"></i><b>8.2.1</b> Visualizing the within-school slopes</a></li>
<li class="chapter" data-level="8.2.2" data-path="more-on-hierarchical-linear-models.html"><a href="more-on-hierarchical-linear-models.html#fitting-the-random-coefficients-2-level-model"><i class="fa fa-check"></i><b>8.2.2</b> Fitting the Random Coefficients 2-level model</a></li>
<li class="chapter" data-level="8.2.3" data-path="more-on-hierarchical-linear-models.html"><a href="more-on-hierarchical-linear-models.html#adding-additional-level-1-predictors-to-the-random-coefficients-model"><i class="fa fa-check"></i><b>8.2.3</b> Adding additional level-1 predictors to the random coefficients model</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="more-on-hierarchical-linear-models.html"><a href="more-on-hierarchical-linear-models.html#intercepts-and-slopes-as-outcomes"><i class="fa fa-check"></i><b>8.3</b> Intercepts and Slopes as Outcomes</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="more-on-hierarchical-linear-models.html"><a href="more-on-hierarchical-linear-models.html#interactions-and-the-iso-model"><i class="fa fa-check"></i><b>8.3.1</b> Interactions and the ISO model</a></li>
<li class="chapter" data-level="8.3.2" data-path="more-on-hierarchical-linear-models.html"><a href="more-on-hierarchical-linear-models.html#mean-ses-and-student-ses"><i class="fa fa-check"></i><b>8.3.2</b> Mean SES and Student SES</a></li>
<li class="chapter" data-level="8.3.3" data-path="more-on-hierarchical-linear-models.html"><a href="more-on-hierarchical-linear-models.html#sector-and-student-ses"><i class="fa fa-check"></i><b>8.3.3</b> Sector and Student SES</a></li>
<li class="chapter" data-level="8.3.4" data-path="more-on-hierarchical-linear-models.html"><a href="more-on-hierarchical-linear-models.html#visualizing-the-mean-ses-effect"><i class="fa fa-check"></i><b>8.3.4</b> Visualizing the mean SES effect</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="more-on-hierarchical-linear-models.html"><a href="more-on-hierarchical-linear-models.html#model-comparison-with-likelihood-ratios-fixed-and-random"><i class="fa fa-check"></i><b>8.4</b> Model comparison with Likelihood Ratios: Fixed and Random</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="more-on-hierarchical-linear-models.html"><a href="more-on-hierarchical-linear-models.html#example-1-lrt-for-fixed-effects"><i class="fa fa-check"></i><b>8.4.1</b> Example 1: LRT for fixed effects</a></li>
<li class="chapter" data-level="8.4.2" data-path="more-on-hierarchical-linear-models.html"><a href="more-on-hierarchical-linear-models.html#example-2-lrt-for-random-effects"><i class="fa fa-check"></i><b>8.4.2</b> Example 2: LRT for random effects</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="more-on-hierarchical-linear-models.html"><a href="more-on-hierarchical-linear-models.html#diagnostics"><i class="fa fa-check"></i><b>8.5</b> Diagnostics</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="using-lme4-to-fit-mlm-to-longitudinal-data.html"><a href="using-lme4-to-fit-mlm-to-longitudinal-data.html"><i class="fa fa-check"></i><b>9</b> Using lme4 to fit MLM to longitudinal data</a>
<ul>
<li class="chapter" data-level="9.1" data-path="using-lme4-to-fit-mlm-to-longitudinal-data.html"><a href="using-lme4-to-fit-mlm-to-longitudinal-data.html#data-description-average-reaction-time-per-day-for-subjects-in-a-sleep-deprivation-study-belenky-et-al.-2003"><i class="fa fa-check"></i><b>9.1</b> Data description: average reaction time per day for subjects in a sleep deprivation study (Belenky et al. 2003)</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="using-lme4-to-fit-mlm-to-longitudinal-data.html"><a href="using-lme4-to-fit-mlm-to-longitudinal-data.html#visualization-of-the-data"><i class="fa fa-check"></i><b>9.1.1</b> Visualization of the data</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="using-lme4-to-fit-mlm-to-longitudinal-data.html"><a href="using-lme4-to-fit-mlm-to-longitudinal-data.html#fitting-the-level-1-model"><i class="fa fa-check"></i><b>9.2</b> Fitting the level-1 model</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="using-lme4-to-fit-mlm-to-longitudinal-data.html"><a href="using-lme4-to-fit-mlm-to-longitudinal-data.html#model-equations"><i class="fa fa-check"></i><b>9.2.1</b> Model Equations</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="using-lme4-to-fit-mlm-to-longitudinal-data.html"><a href="using-lme4-to-fit-mlm-to-longitudinal-data.html#model-building"><i class="fa fa-check"></i><b>9.3</b> Model building</a></li>
<li class="chapter" data-level="9.4" data-path="using-lme4-to-fit-mlm-to-longitudinal-data.html"><a href="using-lme4-to-fit-mlm-to-longitudinal-data.html#model-comparison-and-testing"><i class="fa fa-check"></i><b>9.4</b> Model comparison and testing</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="using-lme4-to-fit-mlm-to-longitudinal-data.html"><a href="using-lme4-to-fit-mlm-to-longitudinal-data.html#option-1-using-confidence-intervals"><i class="fa fa-check"></i><b>9.4.1</b> Option 1: using confidence intervals</a></li>
<li class="chapter" data-level="9.4.2" data-path="using-lme4-to-fit-mlm-to-longitudinal-data.html"><a href="using-lme4-to-fit-mlm-to-longitudinal-data.html#tests"><i class="fa fa-check"></i><b>9.4.2</b> Tests</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="using-lme4-to-fit-mlm-to-longitudinal-data.html"><a href="using-lme4-to-fit-mlm-to-longitudinal-data.html#quadratic-model-with-lmer"><i class="fa fa-check"></i><b>9.5</b> Quadratic model with lmer</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="using-lme4-to-fit-mlm-to-longitudinal-data.html"><a href="using-lme4-to-fit-mlm-to-longitudinal-data.html#a-note-on-quadratic-terms"><i class="fa fa-check"></i><b>9.5.1</b> A note on quadratic terms</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="using-lme4-to-fit-mlm-to-longitudinal-data.html"><a href="using-lme4-to-fit-mlm-to-longitudinal-data.html#summary-of-the-sleepstudy-analysis"><i class="fa fa-check"></i><b>9.6</b> Summary of the sleepstudy analysis</a></li>
<li class="chapter" data-level="9.7" data-path="using-lme4-to-fit-mlm-to-longitudinal-data.html"><a href="using-lme4-to-fit-mlm-to-longitudinal-data.html#preview-of-the-blackmore-data-used-for-assignment-7b"><i class="fa fa-check"></i><b>9.7</b> Preview of the Blackmore data used for Assignment 7b</a>
<ul>
<li class="chapter" data-level="9.7.1" data-path="using-lme4-to-fit-mlm-to-longitudinal-data.html"><a href="using-lme4-to-fit-mlm-to-longitudinal-data.html#a-note-on-the-age-variable-in-blackmore"><i class="fa fa-check"></i><b>9.7.1</b> A note on the age variable in Blackmore</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="longitudinal-models-with-upper-level-predictors.html"><a href="longitudinal-models-with-upper-level-predictors.html"><i class="fa fa-check"></i><b>10</b> Longitudinal models with upper-level predictors</a>
<ul>
<li class="chapter" data-level="10.1" data-path="longitudinal-models-with-upper-level-predictors.html"><a href="longitudinal-models-with-upper-level-predictors.html#overview-2"><i class="fa fa-check"></i><b>10.1</b> Overview</a></li>
<li class="chapter" data-level="10.2" data-path="longitudinal-models-with-upper-level-predictors.html"><a href="longitudinal-models-with-upper-level-predictors.html#part-1-intercepts-and-slopes-as-outcomes"><i class="fa fa-check"></i><b>10.2</b> Part 1: Intercepts and Slopes as Outcomes</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="longitudinal-models-with-upper-level-predictors.html"><a href="longitudinal-models-with-upper-level-predictors.html#a-short-tutorial-on-ggplot2"><i class="fa fa-check"></i><b>10.2.1</b> A short tutorial on ggplot2</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="longitudinal-models-with-upper-level-predictors.html"><a href="longitudinal-models-with-upper-level-predictors.html#adding-level-2-predictors"><i class="fa fa-check"></i><b>10.3</b> Adding level 2 predictors</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="longitudinal-models-with-upper-level-predictors.html"><a href="longitudinal-models-with-upper-level-predictors.html#transforming-the-exercise-variable"><i class="fa fa-check"></i><b>10.3.1</b> Transforming the Exercise Variable</a></li>
<li class="chapter" data-level="10.3.2" data-path="longitudinal-models-with-upper-level-predictors.html"><a href="longitudinal-models-with-upper-level-predictors.html#steps-1-and-2"><i class="fa fa-check"></i><b>10.3.2</b> Steps 1 and 2:</a></li>
<li class="chapter" data-level="10.3.3" data-path="longitudinal-models-with-upper-level-predictors.html"><a href="longitudinal-models-with-upper-level-predictors.html#step-3"><i class="fa fa-check"></i><b>10.3.3</b> Step 3:</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="longitudinal-models-with-upper-level-predictors.html"><a href="longitudinal-models-with-upper-level-predictors.html#summary-1"><i class="fa fa-check"></i><b>10.4</b> Summary</a></li>
<li class="chapter" data-level="10.5" data-path="longitudinal-models-with-upper-level-predictors.html"><a href="longitudinal-models-with-upper-level-predictors.html#adding-level-2-explanatory-variables"><i class="fa fa-check"></i><b>10.5</b> Adding Level-2 Explanatory variables</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="longitudinal-models-with-upper-level-predictors.html"><a href="longitudinal-models-with-upper-level-predictors.html#visualizing-the-transformed-data"><i class="fa fa-check"></i><b>10.5.1</b> Visualizing the transformed data</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="longitudinal-models-with-upper-level-predictors.html"><a href="longitudinal-models-with-upper-level-predictors.html#time-dependent-covariates"><i class="fa fa-check"></i><b>10.6</b> Time dependent covariates</a>
<ul>
<li class="chapter" data-level="10.6.1" data-path="longitudinal-models-with-upper-level-predictors.html"><a href="longitudinal-models-with-upper-level-predictors.html#level-1-time-dependent-sports-predictor"><i class="fa fa-check"></i><b>10.6.1</b> Level-1: Time-dependent sports predictor</a></li>
<li class="chapter" data-level="10.6.2" data-path="longitudinal-models-with-upper-level-predictors.html"><a href="longitudinal-models-with-upper-level-predictors.html#level-2-participant-level-indicator-of-sports-participation"><i class="fa fa-check"></i><b>10.6.2</b> Level-2: Participant-level indicator of sports participation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="multilevel-logistic-regression.html"><a href="multilevel-logistic-regression.html"><i class="fa fa-check"></i><b>11</b> Multilevel logistic regression</a>
<ul>
<li class="chapter" data-level="11.1" data-path="multilevel-logistic-regression.html"><a href="multilevel-logistic-regression.html#unconditional-model"><i class="fa fa-check"></i><b>11.1</b> Unconditional model</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="multilevel-logistic-regression.html"><a href="multilevel-logistic-regression.html#fitting-the-model"><i class="fa fa-check"></i><b>11.1.1</b> Fitting the model</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="multilevel-logistic-regression.html"><a href="multilevel-logistic-regression.html#conditional-model"><i class="fa fa-check"></i><b>11.2</b> Conditional model</a></li>
<li class="chapter" data-level="11.3" data-path="multilevel-logistic-regression.html"><a href="multilevel-logistic-regression.html#interpreting-odds-ratios"><i class="fa fa-check"></i><b>11.3</b> Interpreting odds ratios</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="mlm-v.-gee-for-binary-outcomes.html"><a href="mlm-v.-gee-for-binary-outcomes.html"><i class="fa fa-check"></i><b>12</b> MLM v. GEE for Binary Outcomes</a>
<ul>
<li class="chapter" data-level="12.1" data-path="mlm-v.-gee-for-binary-outcomes.html"><a href="mlm-v.-gee-for-binary-outcomes.html#overview-3"><i class="fa fa-check"></i><b>12.1</b> Overview</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="mlm-v.-gee-for-binary-outcomes.html"><a href="mlm-v.-gee-for-binary-outcomes.html#dataset"><i class="fa fa-check"></i><b>12.1.1</b> Dataset</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="mlm-v.-gee-for-binary-outcomes.html"><a href="mlm-v.-gee-for-binary-outcomes.html#hlm-model"><i class="fa fa-check"></i><b>12.2</b> HLM Model</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="mlm-v.-gee-for-binary-outcomes.html"><a href="mlm-v.-gee-for-binary-outcomes.html#interpreting-odds-ratios-1"><i class="fa fa-check"></i><b>12.2.1</b> Interpreting odds ratios</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="mlm-v.-gee-for-binary-outcomes.html"><a href="mlm-v.-gee-for-binary-outcomes.html#population-average-model-with-gee"><i class="fa fa-check"></i><b>12.3</b> Population Average Model with GEE</a></li>
<li class="chapter" data-level="12.4" data-path="mlm-v.-gee-for-binary-outcomes.html"><a href="mlm-v.-gee-for-binary-outcomes.html#hlm-with-level-2-predictors"><i class="fa fa-check"></i><b>12.4</b> HLM with level-2 predictors</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="mlm-v.-gee-for-binary-outcomes.html"><a href="mlm-v.-gee-for-binary-outcomes.html#random-slopes-1"><i class="fa fa-check"></i><b>12.4.1</b> Random slopes</a></li>
<li class="chapter" data-level="12.4.2" data-path="mlm-v.-gee-for-binary-outcomes.html"><a href="mlm-v.-gee-for-binary-outcomes.html#level-2-predictors"><i class="fa fa-check"></i><b>12.4.2</b> Level 2 predictors</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="mlm-v.-gee-for-binary-outcomes.html"><a href="mlm-v.-gee-for-binary-outcomes.html#compare-to-gee"><i class="fa fa-check"></i><b>12.5</b> Compare to GEE</a>
<ul>
<li class="chapter" data-level="12.5.1" data-path="mlm-v.-gee-for-binary-outcomes.html"><a href="mlm-v.-gee-for-binary-outcomes.html#visualizing-res"><i class="fa fa-check"></i><b>12.5.1</b> Visualizing REs</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Generalized Linear Mixed Models with R: A tutorial</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="introducing-mixed-models-and-the-lme4-package" class="section level1 hasAnchor" number="6">
<h1><span class="header-section-number">6</span> Introducing mixed-models and the lme4 package<a href="introducing-mixed-models-and-the-lme4-package.html#introducing-mixed-models-and-the-lme4-package" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>This tutorial covers very basic <code>lme4</code> syntax as an introduction to random effects. There are some great resources on the web about the syntax as well as the how to distinguish crossed and nested effects using <code>lme4</code>. You can find them here:</p>
<ul>
<li><a href="https://bbolker.github.io/mixedmodels-misc/glmmFAQ.html">Ben Bolker’s FAQ site</a></li>
<li><a href="https://stats.stackexchange.com/a/228814/97844">Cross Validated answer on crossed v. nested</a></li>
</ul>
<div id="options-in-r" class="section level2 hasAnchor" number="6.1">
<h2><span class="header-section-number">6.1</span> Options in R<a href="introducing-mixed-models-and-the-lme4-package.html#options-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>There are several options for including random effects in linear models using <code>R</code>. This is only a partial list:</p>
<ul>
<li><code>nlme</code>: earliest package made for mixed-effects models. Includes the Highschool and Beyond dataset that we will use starting next week</li>
<li><code>lme4</code>: the successor to <code>nlme</code> written by many of the same people. It allows for more complex modeling as well as improved speed. <strong>this is the package we will use</strong></li>
<li><code>glmmTMB</code>: more options for generalized linear mixed models</li>
<li><code>brms</code>: Bayesian approach with a back-end to <code>rstan</code></li>
</ul>
<div id="why-lme4" class="section level3 hasAnchor" number="6.1.1">
<h3><span class="header-section-number">6.1.1</span> Why lme4?<a href="introducing-mixed-models-and-the-lme4-package.html#why-lme4" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For several years <code>lme4</code> has been the most popular option, probably due to its ease of use, good performance with a variety of data sizes and complexity of modeling. It also has good default settings. We will learn that there are many things to be aware of lurking behind the defaults, and that, if you read Ch. 10 in Faraway, inferences using mixed-effects models are not straightforward. This will be a central topic for subsequent weeks. For now, we are interested just in getting used to using this package and what typical code will look like.</p>
</div>
</div>
<div id="a-possible-workflow" class="section level2 hasAnchor" number="6.2">
<h2><span class="header-section-number">6.2</span> A possible workflow<a href="introducing-mixed-models-and-the-lme4-package.html#a-possible-workflow" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This tutorial will focus on 3 things:</p>
<ol style="list-style-type: decimal">
<li>Demonstration of <code>lme4::lmer</code> contrasted with <code>aov()</code> and <code>lm()</code></li>
<li>Walk through of the output from simple random and mixed-effects models</li>
<li>Tour of the methods that operate on the model object (e.g., <code>ranef</code>,<code>predict</code>,<code>residuals</code>, etc.)</li>
</ol>
<div id="high-school-and-beyond" class="section level3 hasAnchor" number="6.2.1">
<h3><span class="header-section-number">6.2.1</span> High School and Beyond<a href="introducing-mixed-models-and-the-lme4-package.html#high-school-and-beyond" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Starting next week, we’ll be using a classic data set, made “famous” by Raudenbush and Bryk in their book. Information about the entire set of studies can be found <a href="https://nces.ed.gov/surveys/hsb/">here</a> and <a href="https://en.wikipedia.org/wiki/High_School_and_Beyond">here</a>.</p>
<p>The data set we will use is a subset of data from the early 1980’s. The outcome is a student’s math achievement score measured using standardized testing, and scored on a logit scale common in testing and item-response theory.</p>
<p>This data set forms the core of the examples in the Raudenbush and Bryk book that we’ll use over the next 4 weeks. We’ll have much more to say about it next week and the week after.</p>
<p>This week, we are only interested in a student’s math score and the fact that students are naturally clustered in <span class="math inline">\(N = 160\)</span> schools. We’ll later learn that some of these schools are public schools and the rest are private, Catholic schools. As an illustration of the distinction between ordinary linear modeling and linear mixed modeling, we’ll also use a student’s socioeconomic status as a predictor of math achievement.</p>
<p>This data set is available via the <code>nlme</code> package as two separate data sets, one at the student level (<code>MathAchieve</code>) and the other at the school level (<code>MathAchSchool</code>). In subsequent weeks, I’ll provide an RData file that will load this directly. Here’s how to construct the data yourself. Note, you will need to install <code>nlme</code> and <code>dplyr</code>.</p>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb198-1"><a href="introducing-mixed-models-and-the-lme4-package.html#cb198-1" tabindex="-1"></a><span class="do">## load the libraries</span></span>
<span id="cb198-2"><a href="introducing-mixed-models-and-the-lme4-package.html#cb198-2" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;nlme&quot;</span>)</span>
<span id="cb198-3"><a href="introducing-mixed-models-and-the-lme4-package.html#cb198-3" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;dplyr&quot;</span>)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:nlme&#39;:
## 
##     collapse</code></pre>
<pre><code>## The following object is masked from &#39;package:MASS&#39;:
## 
##     select</code></pre>
<pre><code>## The following object is masked from &#39;package:car&#39;:
## 
##     recode</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb205-1"><a href="introducing-mixed-models-and-the-lme4-package.html#cb205-1" tabindex="-1"></a><span class="do">## MathAchieve and MathAchSchool are datasets in the nlme package</span></span>
<span id="cb205-2"><a href="introducing-mixed-models-and-the-lme4-package.html#cb205-2" tabindex="-1"></a><span class="co"># ?MathAchieve</span></span>
<span id="cb205-3"><a href="introducing-mixed-models-and-the-lme4-package.html#cb205-3" tabindex="-1"></a><span class="co"># ?MathAchSchool</span></span>
<span id="cb205-4"><a href="introducing-mixed-models-and-the-lme4-package.html#cb205-4" tabindex="-1"></a></span>
<span id="cb205-5"><a href="introducing-mixed-models-and-the-lme4-package.html#cb205-5" tabindex="-1"></a><span class="co"># Make the school-level mean(SES) variable for later use</span></span>
<span id="cb205-6"><a href="introducing-mixed-models-and-the-lme4-package.html#cb205-6" tabindex="-1"></a>MathAchieve <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(School) <span class="sc">%&gt;%</span></span>
<span id="cb205-7"><a href="introducing-mixed-models-and-the-lme4-package.html#cb205-7" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean.ses =</span> <span class="fu">mean</span>(SES)) <span class="ot">-&gt;</span> Temp</span>
<span id="cb205-8"><a href="introducing-mixed-models-and-the-lme4-package.html#cb205-8" tabindex="-1"></a>Temp <span class="ot">&lt;-</span> <span class="fu">merge</span>(MathAchSchool, Temp, <span class="at">by=</span><span class="st">&quot;School&quot;</span>)</span>
<span id="cb205-9"><a href="introducing-mixed-models-and-the-lme4-package.html#cb205-9" tabindex="-1"></a><span class="co"># brief(Temp)</span></span>
<span id="cb205-10"><a href="introducing-mixed-models-and-the-lme4-package.html#cb205-10" tabindex="-1"></a></span>
<span id="cb205-11"><a href="introducing-mixed-models-and-the-lme4-package.html#cb205-11" tabindex="-1"></a><span class="co"># Merge the data to get the single file</span></span>
<span id="cb205-12"><a href="introducing-mixed-models-and-the-lme4-package.html#cb205-12" tabindex="-1"></a>HSB <span class="ot">&lt;-</span> <span class="fu">merge</span>(Temp[, <span class="fu">c</span>(<span class="st">&quot;School&quot;</span>, <span class="st">&quot;Sector&quot;</span>, <span class="st">&quot;mean.ses&quot;</span>,<span class="st">&quot;Size&quot;</span>,<span class="st">&quot;HIMINTY&quot;</span>)],</span>
<span id="cb205-13"><a href="introducing-mixed-models-and-the-lme4-package.html#cb205-13" tabindex="-1"></a>             MathAchieve[, <span class="fu">c</span>(<span class="st">&quot;School&quot;</span>,<span class="st">&quot;Sex&quot;</span>,<span class="st">&quot;SES&quot;</span>,<span class="st">&quot;MathAch&quot;</span>,<span class="st">&quot;Minority&quot;</span>)], <span class="at">by=</span><span class="st">&quot;School&quot;</span>)</span>
<span id="cb205-14"><a href="introducing-mixed-models-and-the-lme4-package.html#cb205-14" tabindex="-1"></a><span class="fu">names</span>(HSB) <span class="ot">&lt;-</span> <span class="fu">tolower</span>(<span class="fu">names</span>(HSB))</span>
<span id="cb205-15"><a href="introducing-mixed-models-and-the-lme4-package.html#cb205-15" tabindex="-1"></a></span>
<span id="cb205-16"><a href="introducing-mixed-models-and-the-lme4-package.html#cb205-16" tabindex="-1"></a><span class="co"># make a level 1 variables that is group-mean (school) centered for SES of the student</span></span>
<span id="cb205-17"><a href="introducing-mixed-models-and-the-lme4-package.html#cb205-17" tabindex="-1"></a>HSB<span class="sc">$</span>cses <span class="ot">&lt;-</span> <span class="fu">with</span>(HSB, ses <span class="sc">-</span> mean.ses)</span>
<span id="cb205-18"><a href="introducing-mixed-models-and-the-lme4-package.html#cb205-18" tabindex="-1"></a></span>
<span id="cb205-19"><a href="introducing-mixed-models-and-the-lme4-package.html#cb205-19" tabindex="-1"></a><span class="co"># Define levels of Sector</span></span>
<span id="cb205-20"><a href="introducing-mixed-models-and-the-lme4-package.html#cb205-20" tabindex="-1"></a>HSB<span class="sc">$</span>sector <span class="ot">&lt;-</span> <span class="fu">factor</span>(HSB<span class="sc">$</span>sector, <span class="at">levels=</span><span class="fu">c</span>(<span class="st">&quot;Public&quot;</span>, <span class="st">&quot;Catholic&quot;</span>))</span></code></pre></div>
<p>Here’s a quick look at the overall structure of the data.</p>
<pre><code>## &#39;data.frame&#39;:    7185 obs. of  10 variables:
##  $ school  : Factor w/ 160 levels &quot;1224&quot;,&quot;1288&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...
##  $ sector  : Factor w/ 2 levels &quot;Public&quot;,&quot;Catholic&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ mean.ses: num  -0.434 -0.434 -0.434 -0.434 -0.434 ...
##  $ size    : num  842 842 842 842 842 842 842 842 842 842 ...
##  $ himinty : Factor w/ 2 levels &quot;0&quot;,&quot;1&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ sex     : Factor w/ 2 levels &quot;Male&quot;,&quot;Female&quot;: 2 2 1 1 1 1 2 1 2 1 ...
##  $ ses     : num  -1.528 -0.588 -0.528 -0.668 -0.158 ...
##  $ mathach : num  5.88 19.71 20.35 8.78 17.9 ...
##  $ minority: Factor w/ 2 levels &quot;No&quot;,&quot;Yes&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ cses    : num  -1.0936 -0.1536 -0.0936 -0.2336 0.2764 ...</code></pre>
<p>The grouping factor is <code>school</code> and the outcome is <code>mathach</code> so a random-effects ANOVA would be specified (using this week’s notation) as:</p>
<p><span class="math display">\[
Y_{ij} = \mu + \alpha_{j} + \epsilon_{ij}
\]</span></p>
<p>where <span class="math inline">\(Y_{ij}\)</span> is the <span class="math inline">\(i^{th}\)</span> student’s math achievement score in school <span class="math inline">\(j\)</span> and <span class="math inline">\(\mu\)</span> is the grand mean math achievement across students and schools. The <span class="math inline">\(\alpha_{j}\)</span>’s are the school random effects and the <span class="math inline">\(\epsilon_{ij}\)</span>’s are the student-level random errors</p>
<p>This is a classic nested design as a student exists in one and only one school</p>
<p>Let’s look at the ANOVA estimators, the REML estimates, and the ML estimates for two models:</p>
<ol style="list-style-type: decimal">
<li>A one-way anova as specified above</li>
<li>A mixed-effects model with student SES (centered within the school as <code>cses</code>) as a single predictor</li>
</ol>
</div>
</div>
<div id="model-1-one-way-random-effects-anova-using-reml" class="section level2 hasAnchor" number="6.3">
<h2><span class="header-section-number">6.3</span> Model 1: one-way random-effects ANOVA using REML<a href="introducing-mixed-models-and-the-lme4-package.html#model-1-one-way-random-effects-anova-using-reml" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>To run this code, you will first need to install <code>lme4</code> using either <code>install.packages</code> or using the Packages tab. Each time you use <code>lme4</code> you will need to load it</p>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb207-1"><a href="introducing-mixed-models-and-the-lme4-package.html#cb207-1" tabindex="-1"></a><span class="fu">library</span>(lme4) <span class="co"># load the package</span></span></code></pre></div>
<pre><code>## Loading required package: Matrix</code></pre>
<pre><code>## 
## Attaching package: &#39;lme4&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:nlme&#39;:
## 
##     lmList</code></pre>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb211-1"><a href="introducing-mixed-models-and-the-lme4-package.html#cb211-1" tabindex="-1"></a>mod1_re <span class="ot">&lt;-</span> <span class="fu">lmer</span>(mathach <span class="sc">~</span> (<span class="dv">1</span><span class="sc">|</span>school), <span class="at">data =</span> HSB) <span class="co"># fit the model</span></span></code></pre></div>
<p>The syntax is very simple, and we’ll go through more complex versions in the coming weeks. In <code>lme4</code> random effects are specified in parentheses using the mid-bar <code>|</code></p>
<p>So <code>(1|school)</code> means fit a random effect (intercept) of school (allow the mean outcome to vary across schools).</p>
<ul>
<li>Note, if we had a crossed design, with <code>teacher</code> as a second factor, we’d have: <code>(1|school) + (1|teacher)</code> for schools <em>crossed</em> with teachers</li>
<li>Additional levels of nesting use <code>\</code>: <code>(1|school/teacher)</code> or explicitly the <code>:</code> as in<code>(1|school) + (1|school:teacher)</code> for teachers <em>nested</em> in schools</li>
</ul>
<p>The full output of this model is somewhat boring, but includes important information:</p>
<ol style="list-style-type: decimal">
<li>Estimates of <span class="math inline">\(\hat{\sigma}^{2}_{\alpha}\)</span> and <span class="math inline">\(\hat{\sigma}^{2}_{\epsilon}\)</span></li>
<li>Estimates of the grand mean (only works for a model with no predictors)</li>
</ol>
<p>Note, the default for <code>lmer</code> is to use REML. This is what we want currently as it will give us the best estimate of the variance of the random effects.</p>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb212-1"><a href="introducing-mixed-models-and-the-lme4-package.html#cb212-1" tabindex="-1"></a><span class="fu">summary</span>(mod1_re)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: mathach ~ (1 | school)
##    Data: HSB
## 
## REML criterion at convergence: 47116.8
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.0631 -0.7539  0.0267  0.7606  2.7426 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  school   (Intercept)  8.614   2.935   
##  Residual             39.148   6.257   
## Number of obs: 7185, groups:  school, 160
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)  12.6370     0.2444   51.71</code></pre>
<p>Note also, that the estimate of the intercept is not the average <code>mathach</code> across the students, as that ignores the grouping:</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="introducing-mixed-models-and-the-lme4-package.html#cb214-1" tabindex="-1"></a><span class="fu">mean</span>(HSB<span class="sc">$</span>mathach)</span></code></pre></div>
<pre><code>## [1] 12.74785</code></pre>
<p>Instead, we’ll learn next week, that with unequal group sizes <span class="math inline">\(n_j\)</span>, the intercept will be a <em>precision-weighted average</em> of the group means. Essentially, groups with smaller variance (greater precision) contribute more to the overall estimate of the intercept. This is in contrast with other weighting techniques that just utilize sample-size.</p>
</div>
<div id="quasi-anova-estimator" class="section level2 hasAnchor" number="6.4">
<h2><span class="header-section-number">6.4</span> Quasi-ANOVA estimator<a href="introducing-mixed-models-and-the-lme4-package.html#quasi-anova-estimator" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>If we use <code>aov()</code> to estimate the variance, we won’t get what we: the ANOVA estimator does not work with unequal group size.</p>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb216-1"><a href="introducing-mixed-models-and-the-lme4-package.html#cb216-1" tabindex="-1"></a>amod <span class="ot">&lt;-</span> <span class="fu">aov</span>(mathach <span class="sc">~</span> <span class="fu">Error</span>(school), <span class="at">data =</span> HSB)</span>
<span id="cb216-2"><a href="introducing-mixed-models-and-the-lme4-package.html#cb216-2" tabindex="-1"></a><span class="fu">summary</span>(amod)</span></code></pre></div>
<pre><code>## 
## Error: school
##            Df Sum Sq Mean Sq F value Pr(&gt;F)
## Residuals 159  64907   408.2               
## 
## Error: Within
##             Df Sum Sq Mean Sq F value Pr(&gt;F)
## Residuals 7025 274970   39.14</code></pre>
<div id="unrestricted-maximum-likelihood" class="section level3 hasAnchor" number="6.4.1">
<h3><span class="header-section-number">6.4.1</span> (unrestricted) Maximum Likelihood<a href="introducing-mixed-models-and-the-lme4-package.html#unrestricted-maximum-likelihood" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We’ll learn in later weeks that comparing models with different fixed effects must be done with <code>REML = TRUE</code> (ie., using <code>ML</code> or “unrestricted” maximum likelihood estimation). For large data sets, the differences are very slight. For example:</p>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb218-1"><a href="introducing-mixed-models-and-the-lme4-package.html#cb218-1" tabindex="-1"></a>mod1_ml <span class="ot">&lt;-</span> <span class="fu">lmer</span>(mathach <span class="sc">~</span> (<span class="dv">1</span><span class="sc">|</span>school), <span class="at">data =</span> HSB, <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb218-2"><a href="introducing-mixed-models-and-the-lme4-package.html#cb218-2" tabindex="-1"></a><span class="fu">summary</span>(mod1_ml)</span></code></pre></div>
<pre><code>## Linear mixed model fit by maximum likelihood  [&#39;lmerMod&#39;]
## Formula: mathach ~ (1 | school)
##    Data: HSB
## 
##       AIC       BIC    logLik -2*log(L)  df.resid 
##   47121.8   47142.4  -23557.9   47115.8      7182 
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -3.06262 -0.75365  0.02676  0.76070  2.74184 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  school   (Intercept)  8.553   2.925   
##  Residual             39.148   6.257   
## Number of obs: 7185, groups:  school, 160
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)  12.6371     0.2436   51.87</code></pre>
<p>Note, the school-level variance is estimated to be smaller (<span class="math inline">\(8.55\)</span> v. <span class="math inline">\(8.64\)</span>) but the residual is the same. Also note that we now have AIC, BIC, a log likelihood, deviance, and residual df. This is because we have a full ML model. We do not get that information from <code>REML</code>.</p>
</div>
<div id="intraclass-correlation" class="section level3 hasAnchor" number="6.4.2">
<h3><span class="header-section-number">6.4.2</span> Intraclass correlation<a href="introducing-mixed-models-and-the-lme4-package.html#intraclass-correlation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>One of the main outcomes of the one-way random effects ANOVA, or <em>unconditional</em> model is the ability to compute the intraclass correlation. Recall that we can compute it using the estimates from unconditional model (we should use the REML estimates):</p>
<p><span class="math display">\[
ICC = \frac{\hat{\sigma}^{2}_{\alpha}}{\hat{\sigma}^{2}_{\alpha} + \hat{\sigma}^{2}_{\epsilon}}
\]</span></p>
<p>From our output, we see that <span class="math inline">\(\hat{\sigma}^{2}_{\alpha} = 8.614\)</span> and <span class="math inline">\(\hat{\sigma}^{2}_{\epsilon} = 39.148\)</span>. So the unconditional intraclass correlation is:</p>
<p><span class="math display">\[
\begin{aligned}
ICC &amp; = \frac{\hat{\sigma}^{2}_{\alpha}}{\hat{\sigma}^{2}_{\alpha} + \hat{\sigma}^{2}_{\epsilon}} \\
    &amp; = \frac{8.614}{8.614 +39.148}\\
    &amp; = 0.18
\end{aligned}
\]</span></p>
<p>Remember, this is an estimate of the correlation between two randomly selected students’ math scores from within the same school.</p>
</div>
</div>
<div id="bootstrapped-confidence-intervals" class="section level2 hasAnchor" number="6.5">
<h2><span class="header-section-number">6.5</span> Bootstrapped confidence intervals<a href="introducing-mixed-models-and-the-lme4-package.html#bootstrapped-confidence-intervals" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We’ll talk more about the complexity of inference procedures starting next week. The short version is that bootstrapped confidence intervals are probably the best, though other methods also work well. Either way, bootstrapped CI’s are great for simple models. They may take a <strong>very</strong> long time to compute for complex models, however.</p>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb220-1"><a href="introducing-mixed-models-and-the-lme4-package.html#cb220-1" tabindex="-1"></a><span class="fu">confint</span>(mod1_re, <span class="at">method =</span> <span class="st">&quot;boot&quot;</span>)</span></code></pre></div>
<pre><code>## Computing bootstrap confidence intervals ...</code></pre>
<pre><code>##                 2.5 %    97.5 %
## .sig01       2.594500  3.354701
## .sigma       6.152638  6.361720
## (Intercept) 12.158422 13.085090</code></pre>
<p>In the above, <code>.sig01</code> is the standard deviation of the random effects of school (<span class="math inline">\(\sigma_{\alpha}\)</span>). If you want variances, you must square the end points. However, standard deviation is more interpretable. Also, <code>.sigma</code> is the CI for the residual standard deviation.</p>
<p>The random effects CI’s will always be on top of the <code>confint</code> output. Fixed effects will be listed next. Here, we only have one fixed effect, the overall grand mean <span class="math inline">\(\mu\)</span> which we will learn can also be parameterized as a regression intercept <span class="math inline">\(\gamma_{00}\)</span>.</p>
<p>We’ll also discuss the assumption of normality of the random effects next week. The intercept and standard deviation of the random effects together give us information about the unconditional distribution of mean math scores:</p>
<p><span class="math inline">\(\hat{\mu}_{..} = 12.64\)</span>, <span class="math inline">\(95\% \text{ CI } (12.16, 13.14)\)</span>
<span class="math inline">\(\text{SD} = 2.94\)</span>, <span class="math inline">\(95\% \text{ CI } (2.55, 3.26)\)</span></p>
<p>We can see in the plot below, that theoretically, most (<span class="math inline">\(\sim 68 \%\)</span>) of the schools have mean math achievement between <span class="math inline">\(\sim 9.70\)</span> and <span class="math inline">\(\sim 15.50\)</span></p>
<p><img src="_main_files/figure-html/ranef_dist06-1.png" width="672" /></p>
</div>
<div id="linear-mixed-effects" class="section level2 hasAnchor" number="6.6">
<h2><span class="header-section-number">6.6</span> Linear mixed-effects<a href="introducing-mixed-models-and-the-lme4-package.html#linear-mixed-effects" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>For illustration, we’ll fit a model where a student’s math achievement is a function of their group-centered SES (<code>cses</code>). We’ll learn some different terminology for this in the next two weeks, but here, we’re going to contrast the fixed-effect estimate from <code>lmer</code> with that from <code>lm</code>.</p>
<p>Here’s how we include a predictor in <code>lmer</code>:</p>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb223-1"><a href="introducing-mixed-models-and-the-lme4-package.html#cb223-1" tabindex="-1"></a>mod2_re <span class="ot">&lt;-</span> <span class="fu">lmer</span>(mathach <span class="sc">~</span> cses <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>school), <span class="at">data =</span> HSB)</span>
<span id="cb223-2"><a href="introducing-mixed-models-and-the-lme4-package.html#cb223-2" tabindex="-1"></a><span class="fu">summary</span>(mod2_re)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: mathach ~ cses + (1 | school)
##    Data: HSB
## 
## REML criterion at convergence: 46724
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.0969 -0.7322  0.0194  0.7572  2.9147 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  school   (Intercept)  8.672   2.945   
##  Residual             37.010   6.084   
## Number of obs: 7185, groups:  school, 160
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)  12.6361     0.2445   51.68
## cses          2.1912     0.1087   20.17
## 
## Correlation of Fixed Effects:
##      (Intr)
## cses 0.000</code></pre>
<p>Now, with <code>lm()</code> we ignore the fact that students are grouped</p>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb225-1"><a href="introducing-mixed-models-and-the-lme4-package.html#cb225-1" tabindex="-1"></a>mod2_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(mathach <span class="sc">~</span> cses, <span class="at">data =</span> HSB)</span>
<span id="cb225-2"><a href="introducing-mixed-models-and-the-lme4-package.html#cb225-2" tabindex="-1"></a><span class="fu">summary</span>(mod2_lm)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mathach ~ cses, data = HSB)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -17.8660  -5.1165   0.2966   5.3880  14.8705 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 12.74785    0.07933  160.69   &lt;2e-16 ***
## cses         2.19117    0.12010   18.24   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.725 on 7183 degrees of freedom
## Multiple R-squared:  0.04429,    Adjusted R-squared:  0.04415 
## F-statistic: 332.8 on 1 and 7183 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Note that the <code>cses</code> effects are similar, but with different standard errors, and that the intercept estimate is essentially the sample average math achievement in <code>lm</code>, ignoring the grouping by school. We also do not get any information about variability in the school means.</p>
<div id="random-effects-estimates" class="section level3 hasAnchor" number="6.6.1">
<h3><span class="header-section-number">6.6.1</span> Random effects estimates<a href="introducing-mixed-models-and-the-lme4-package.html#random-effects-estimates" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s go back to the first model and see some of the random effects estimates:</p>
<div class="sourceCode" id="cb227"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb227-1"><a href="introducing-mixed-models-and-the-lme4-package.html#cb227-1" tabindex="-1"></a>ran <span class="ot">&lt;-</span> <span class="fu">ranef</span>(mod1_re)</span>
<span id="cb227-2"><a href="introducing-mixed-models-and-the-lme4-package.html#cb227-2" tabindex="-1"></a>ran<span class="sc">$</span>school<span class="sc">$</span><span class="st">`</span><span class="at">(Intercept)</span><span class="st">`</span>[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]</span></code></pre></div>
<pre><code>##  [1] -2.6639348  0.7394098 -4.5684656  2.9485171  0.4939461 -1.2425116 -2.5023497  6.2682432  4.9621083
## [10]  3.6965749</code></pre>
<p>These are simply the amount by which school <span class="math inline">\(J\)</span> deviates from the estimated mean of <span class="math inline">\(12.64\)</span>.</p>
<p>We can also get the estimated school means. Note, these are NOT the actual means of the scores within each school. In later weeks, we’ll discuss that these are Empirical Bayes estimates, which are <em>shrinkage</em> estimates. When a school’s mean is not precisely captured in the sample, the estimate <strong>shrinks</strong> toward the grand mean (<span class="math inline">\(12.64\)</span>). When a school’s estimate is precise, the estimated mean is less influenced by the grand mean.</p>
<p>In this way, estimates of smaller or less precisely estimated schools take information from the rest of the distribution.</p>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb229-1"><a href="introducing-mixed-models-and-the-lme4-package.html#cb229-1" tabindex="-1"></a>cof <span class="ot">&lt;-</span> <span class="fu">coef</span>(mod1_re)</span>
<span id="cb229-2"><a href="introducing-mixed-models-and-the-lme4-package.html#cb229-2" tabindex="-1"></a>cof<span class="sc">$</span>school<span class="sc">$</span><span class="st">`</span><span class="at">(Intercept)</span><span class="st">`</span>[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]</span></code></pre></div>
<pre><code>##  [1]  9.973039 13.376384  8.068508 15.585491 13.130920 11.394462 10.134624 18.905217 17.599082
## [10] 16.333549</code></pre>
<p>As we see, the estimated mean math achievement in school <code>1308</code> is <span class="math inline">\(15.59\)</span> while the actual sample average is:</p>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb231-1"><a href="introducing-mixed-models-and-the-lme4-package.html#cb231-1" tabindex="-1"></a><span class="fu">mean</span>(HSB<span class="sc">$</span>mathach[HSB<span class="sc">$</span>school <span class="sc">==</span> <span class="st">&quot;1308&quot;</span>])</span></code></pre></div>
<pre><code>## [1] 16.2555</code></pre>
<p>Summary:</p>
<ol style="list-style-type: decimal">
<li>We have now started to use <code>lmer</code> the main function for fitting mixed-effects models with <code>REML</code> (and with <code>ML</code>)</li>
<li>We’ve seen some simple output and computed the intraclass correlation</li>
<li>We’ve discussed a bit about the distribution of random effects and their estimates</li>
</ol>
<p>Next week, we’ll pull this together in the context of an actual research question.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="model-fit-and-assumptions-for-glms.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="mixed-models-as-hierarchical-linear-models.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
